USE [master]
GO

CREATE DATABASE [GestionPersonalProinsa]
GO

USE [GestionPersonalProinsa]
GO

CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[APROBACIONSOLICITUD]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[APROBACIONSOLICITUD](
	[ID_APROBACIONSOLICITUD] [bigint] IDENTITY(1,1) NOT NULL,
	[FECHA_APROBACIONSOLICITUD] [datetime] NOT NULL,
	[SECUENCIA] [int] NULL,
	[RESPUESTA_SOLICITUD] [char](10) NOT NULL,
	[COMENTARIO] [varchar](200) NULL,
	[ENCARGADO_APROBACION_ID] [bigint] NOT NULL,
	[SOLICITUD_ID] [bigint] NOT NULL,
 CONSTRAINT [PK_APROBACIONSOLICITUD_ID] PRIMARY KEY CLUSTERED 
(
	[ID_APROBACIONSOLICITUD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AspNetRoleClaims]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetRoleClaims](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[RoleId] [nvarchar](450) NOT NULL,
	[ClaimType] [nvarchar](max) NULL,
	[ClaimValue] [nvarchar](max) NULL,
 CONSTRAINT [PK_AspNetRoleClaims] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AspNetRoles]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetRoles](
	[Id] [nvarchar](450) NOT NULL,
	[Name] [nvarchar](256) NULL,
	[NormalizedName] [nvarchar](256) NULL,
	[ConcurrencyStamp] [nvarchar](max) NULL,
 CONSTRAINT [PK_AspNetRoles] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AspNetUserClaims]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetUserClaims](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [nvarchar](450) NOT NULL,
	[ClaimType] [nvarchar](max) NULL,
	[ClaimValue] [nvarchar](max) NULL,
 CONSTRAINT [PK_AspNetUserClaims] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AspNetUserLogins]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetUserLogins](
	[LoginProvider] [nvarchar](450) NOT NULL,
	[ProviderKey] [nvarchar](450) NOT NULL,
	[ProviderDisplayName] [nvarchar](max) NULL,
	[UserId] [nvarchar](450) NOT NULL,
 CONSTRAINT [PK_AspNetUserLogins] PRIMARY KEY CLUSTERED 
(
	[LoginProvider] ASC,
	[ProviderKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AspNetUserRoles]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetUserRoles](
	[UserId] [nvarchar](450) NOT NULL,
	[RoleId] [nvarchar](450) NOT NULL,
 CONSTRAINT [PK_AspNetUserRoles] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC,
	[RoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AspNetUsers]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetUsers](
	[Id] [nvarchar](450) NOT NULL,
	[UserName] [nvarchar](256) NULL,
	[NormalizedUserName] [nvarchar](256) NULL,
	[Email] [nvarchar](256) NULL,
	[NormalizedEmail] [nvarchar](256) NULL,
	[EmailConfirmed] [bit] NOT NULL,
	[PasswordHash] [nvarchar](max) NULL,
	[SecurityStamp] [nvarchar](max) NULL,
	[ConcurrencyStamp] [nvarchar](max) NULL,
	[PhoneNumber] [nvarchar](max) NULL,
	[PhoneNumberConfirmed] [bit] NOT NULL,
	[TwoFactorEnabled] [bit] NOT NULL,
	[LockoutEnd] [datetimeoffset](7) NULL,
	[LockoutEnabled] [bit] NOT NULL,
	[AccessFailedCount] [int] NOT NULL,
 CONSTRAINT [PK_AspNetUsers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AspNetUserTokens]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetUserTokens](
	[UserId] [nvarchar](450) NOT NULL,
	[LoginProvider] [nvarchar](450) NOT NULL,
	[Name] [nvarchar](450) NOT NULL,
	[Value] [nvarchar](max) NULL,
 CONSTRAINT [PK_AspNetUserTokens] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC,
	[LoginProvider] ASC,
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CAPACITACION]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CAPACITACION](
	[ID_CAPACION] [bigint] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [varchar](100) NULL,
	[INSTITUCION] [varchar](100) NULL,
	[LINK] [varchar](100) NULL,
	[CERTIFICACION] [varchar](100) NULL,
	[FECHA_FINALIZACION] [datetime] NULL,
	[CANTIDAD_HORAS] [int] NULL,
	[ESTADO] [bit] NULL,
 CONSTRAINT [PK_CAPACITACION_ID] PRIMARY KEY CLUSTERED 
(
	[ID_CAPACION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CARGO]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CARGO](
	[ID_CARGO] [bigint] IDENTITY(1,1) NOT NULL,
	[NOMBRE_CARGO] [varchar](50) NULL,
	[DESCRIPCION] [varchar](200) NULL,
 CONSTRAINT [PK_CARGO_ID] PRIMARY KEY CLUSTERED 
(
	[ID_CARGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CORREO]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CORREO](
	[ID_CORREO] [bigint] IDENTITY(1,1) NOT NULL,
	[CORREO] [varchar](255) NULL,
 CONSTRAINT [PK_CORREO_ID] PRIMARY KEY CLUSTERED 
(
	[ID_CORREO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DB_ERRORES]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DB_ERRORES](
	[ErrorID] [int] IDENTITY(1,1) NOT NULL,
	[UserName] [varchar](100) NULL,
	[ErrorNumber] [int] NULL,
	[ErrorState] [int] NULL,
	[ErrorSeverity] [int] NULL,
	[ErrorLine] [int] NULL,
	[ErrorProcedure] [varchar](max) NULL,
	[ErrorMessage] [varchar](max) NULL,
	[ErrorDateTime] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DEDUCCION]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEDUCCION](
	[ID_DEDUCCION] [bigint] IDENTITY(1,1) NOT NULL,
	[NOMBRE_INGRESO] [varchar](50) NULL,
	[DESCRIPCION] [varchar](200) NULL,
	[PORCENTAJE] [decimal](10, 2) NULL,
 CONSTRAINT [PK_DEDUCCION_ID] PRIMARY KEY CLUSTERED 
(
	[ID_DEDUCCION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DEDUCCIONNOMINA]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEDUCCIONNOMINA](
	[ID_DEDUCCIONNOMINA] [bigint] IDENTITY(1,1) NOT NULL,
	[MONTO] [decimal](10, 2) NULL,
	[DETALLE] [varchar](100) NULL,
	[DEDUCCION_ID] [bigint] NULL,
 CONSTRAINT [PK_DEDUCCIONNOMINA_ID] PRIMARY KEY CLUSTERED 
(
	[ID_DEDUCCIONNOMINA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DEPARTAMENTO]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEPARTAMENTO](
	[ID_DEPARTAMENTO] [bigint] IDENTITY(1,1) NOT NULL,
	[NOMBRE_DEPARTAMENTO] [varchar](50) NULL,
	[DESCRIPCION] [varchar](100) NOT NULL,
 CONSTRAINT [PK_DEPARTAMENTO_ID] PRIMARY KEY CLUSTERED 
(
	[ID_DEPARTAMENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DEPARTAMENTOSUPERVISOR]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEPARTAMENTOSUPERVISOR](
	[ID_DEPARTAMENTOSUPERVISOR] [bigint] IDENTITY(1,1) NOT NULL,
	[EMPLEADO_ID] [bigint] NOT NULL,
	[DEPARTAMENTO_ID] [bigint] NOT NULL,
 CONSTRAINT [PK_DEPARTAMENTOSUPERVISOR_ID] PRIMARY KEY CLUSTERED 
(
	[ID_DEPARTAMENTOSUPERVISOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DIRRECCION]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIRRECCION](
	[ID_DIRECCION] [bigint] IDENTITY(1,1) NOT NULL,
	[DIRRECION] [varchar](600) NULL,
 CONSTRAINT [PK_DIRRECCION_ID] PRIMARY KEY CLUSTERED 
(
	[ID_DIRECCION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EMPLEADO]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EMPLEADO](
	[ID_EMPLEADO] [bigint] IDENTITY(1,1) NOT NULL,
	[IDENTIFICACION] [int] NULL,
	[NOMBRECOMPLETO] [varchar](250) NULL,
	[FECHA_NACIMIENTO] [datetime] NULL,
	[FECHA_INGRESO] [datetime] NULL,
	[FOTO] [varchar](250) NULL,
	[SALARIO] [decimal](10, 2) NULL,
	[SALDO_VACACIONES] [int] NULL,
	[CARGO_ID] [bigint] NULL,
	[CORREO_ID] [bigint] NOT NULL,
	[HORARIOLABORAL_ID] [bigint] NULL,
	[DEPARTAMENTO_ID] [bigint] NULL,
	[ESTADO] [bit] NULL,
 CONSTRAINT [PK_EMPLEADO_ID] PRIMARY KEY CLUSTERED 
(
	[ID_EMPLEADO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EMPLEADOCAPACITACION]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EMPLEADOCAPACITACION](
	[ID_EMPLEADOCAPACITACION] [bigint] IDENTITY(1,1) NOT NULL,
	[CAPACITACION_ID] [bigint] NOT NULL,
	[EMPLEADO_ID] [bigint] NOT NULL,
 CONSTRAINT [PK_EMPLEADOCAPACITACION_ID] PRIMARY KEY CLUSTERED 
(
	[ID_EMPLEADOCAPACITACION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EMPLEADODIRRECCION]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EMPLEADODIRRECCION](
	[ID_EMPLEADODIRRECCION] [bigint] IDENTITY(1,1) NOT NULL,
	[EMPLEADO_ID] [bigint] NOT NULL,
	[DIRRECION_ID] [bigint] NOT NULL,
 CONSTRAINT [PK_EMPLEADODIRRECCION_ID] PRIMARY KEY CLUSTERED 
(
	[ID_EMPLEADODIRRECCION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EMPLEADODOCUMENTO]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EMPLEADODOCUMENTO](
	[ID_EMPLEADODOCUMENTO] [bigint] IDENTITY(1,1) NOT NULL,
	[NOMBRE_DOCUMENTO] [varchar](50) NULL,
	[COMENTARIO] [varchar](200) NULL,
	[TIPODOCUMENTO_ID] [bigint] NULL,
	[EMPLEADO_ID] [bigint] NULL,
 CONSTRAINT [PK_EMPLEADODOCUMENTO_ID] PRIMARY KEY CLUSTERED 
(
	[ID_EMPLEADODOCUMENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EMPLEADOTELEFONO]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EMPLEADOTELEFONO](
	[ID_EMPLEADOTELEFONO] [bigint] IDENTITY(1,1) NOT NULL,
	[EMPLEADO_ID] [bigint] NOT NULL,
	[TELEFONO_ID] [bigint] NOT NULL,
 CONSTRAINT [PK_EMPLEADOTELEFONO_ID] PRIMARY KEY CLUSTERED 
(
	[ID_EMPLEADOTELEFONO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FLUJOAPROBACION]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FLUJOAPROBACION](
	[ID_FLUJOAPROBACION] [bigint] IDENTITY(1,1) NOT NULL,
	[SECUENCIA] [int] NOT NULL,
	[DEPARTAMENTO_APROBACION_ID] [bigint] NULL,
	[DEPARTAMENTO_ID] [bigint] NOT NULL,
 CONSTRAINT [PK_FLUJOAPROBACION_ID] PRIMARY KEY CLUSTERED 
(
	[ID_FLUJOAPROBACION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HORARIOLABORAL]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HORARIOLABORAL](
	[ID_HORARIOLABORAL] [bigint] IDENTITY(1,1) NOT NULL,
	[NOMBREHL] [varchar](50) NOT NULL,
	[DESCRIPCION] [varchar](200) NULL,
	[HORA_INGRESO] [int] NULL,
	[HORA_SALIDA] [int] NULL,
 CONSTRAINT [PK_HORARIOLABORAL_ID] PRIMARY KEY CLUSTERED 
(
	[ID_HORARIOLABORAL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INGRESO]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INGRESO](
	[ID_INGRESO] [bigint] IDENTITY(1,1) NOT NULL,
	[NOMBRE_INGRESO] [varchar](50) NOT NULL,
	[DESCRIPCION] [varchar](200) NULL,
	[MONTO] [decimal](10, 2) NULL,
	[PORCENTAJE] [decimal](10, 2) NULL,
 CONSTRAINT [PK_INGRESO_ID] PRIMARY KEY CLUSTERED 
(
	[ID_INGRESO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INGRESONOMINA]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INGRESONOMINA](
	[ID_INGRESONOMINA] [bigint] IDENTITY(1,1) NOT NULL,
	[MONTO] [decimal](10, 2) NULL,
	[DETALLE] [varchar](100) NULL,
	[INGRESO_ID] [bigint] NULL,
 CONSTRAINT [PK_INGRESONOMINA_ID] PRIMARY KEY CLUSTERED 
(
	[ID_INGRESONOMINA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NOMINA]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NOMINA](
	[ID_NOMINA] [bigint] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [varchar](100) NULL,
	[PERIODO] [varchar](50) NULL,
	[FECHA_CALCULO] [datetime] NULL,
	[FECHA_PAGO] [datetime] NULL,
	[OBSERVACIONES] [varchar](500) NULL,
	[REVISIONES] [int] NULL,
	[FECHACREACION] [datetime] NULL,
	[FECHACAPROBACION] [datetime] NULL,
	[ESTADO] [bit] NULL,
	[HORAS_TRABAJADAS] [int] NULL,
    [HORAS_EXTRA] [int] NULL,
	[SALARIO_BRUTO] [decimal](10, 2) NULL,
	[SALARIO_NETO] [decimal](10, 2) NULL,
	[INGRESONOMINA_ID] [bigint] NOT NULL,
	[DEDUCCIONNOMINA_ID] [bigint] NOT NULL,
	[EMPLEADO_ID] [bigint] NOT NULL,
	[TIPONOMINA_ID] [bigint] NULL,
	[CREADOR_ID] [bigint] NULL,
	[APROBADOR_ID] [bigint] NULL,
CONSTRAINT [PK_NOMINA_ID]
PRIMARY KEY CLUSTERED 
(
	[ID_NOMINA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NOMINADETALLE]    Script Date: 6/10/2024 9:05:07 PM ******/
/****** NOMINADETALLE se unifica con NOMINA ******/

/****** Object:  Table [dbo].[REGISTROACTIVIDAD]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REGISTROACTIVIDAD](
	[ID_REGISTROACTIVIDAD] [bigint] IDENTITY(1,1) NOT NULL,
	[FECHA_INICIO] [datetime] NULL,
	[FECHA_FINAL] [datetime] NULL,
	[DETALLE] [varchar](500) NULL,
	[TIPOACTIVIDAD_ID] [bigint] NOT NULL,
	[EMPLEADO_ID] [bigint] NOT NULL,
 CONSTRAINT [PK_REGISTROACTIVIDAD_ID] PRIMARY KEY CLUSTERED 
(
	[ID_REGISTROACTIVIDAD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SOLICITUD]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SOLICITUD](
	[ID_SOLICITUD] [bigint] IDENTITY(1,1) NOT NULL,
	[FECHA_SOLICITUD] [datetime] NOT NULL,
	[FECHA_INICIO] [datetime] NOT NULL,
	[FECHA_FINAL] [datetime] NOT NULL,
	[COMENTARIO] [varchar](200) NULL,
	[DIAS] [int] NOT NULL,
	[DETALLE] [varchar](300) NULL,
	[ESTADO_SOLICITUD] [char](10) NULL,
	[SOLICITANTE_ID] [bigint] NOT NULL,
	[TIPOSOLICITUD_ID] [bigint] NOT NULL,
 CONSTRAINT [PK_SOLICITUD_ID] PRIMARY KEY CLUSTERED 
(
	[ID_SOLICITUD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TELEFONO]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TELEFONO](
	[ID_TELEFONO] [bigint] IDENTITY(1,1) NOT NULL,
	[TELEFONO] [varchar](22) NULL,
 CONSTRAINT [PK_TELEFONO_ID] PRIMARY KEY CLUSTERED 
(
	[ID_TELEFONO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TIPOACTIVIDAD]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPOACTIVIDAD](
	[ID_TIPOACTIVIDAD] [bigint] IDENTITY(1,1) NOT NULL,
	[NOMBRE_TIPO_CTIVIDAD] [varchar](50) NULL,
	[DESCRIPCION] [varchar](100) NULL,
 CONSTRAINT [PK_TIPOACTIVIDAD_ID] PRIMARY KEY CLUSTERED 
(
	[ID_TIPOACTIVIDAD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TIPODOCUMENTO]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPODOCUMENTO](
	[ID_TIPODOCUMENTO] [bigint] IDENTITY(1,1) NOT NULL,
	[NOMBRE_TIPODOCUMENTO] [varchar](50) NOT NULL,
	[DESCRIPCION] [varchar](200) NULL,
 CONSTRAINT [PK_TIPODOCUMENTO_ID] PRIMARY KEY CLUSTERED 
(
	[ID_TIPODOCUMENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TIPONOMINA]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPONOMINA](
	[ID_TIPONOMINA] [bigint] IDENTITY(1,1) NOT NULL,
	[NOMBRE_NOMINA] [varchar](50) NULL,
	[DESCRIPCION] [varchar](200) NULL,
 CONSTRAINT [PK_TIPONOMINA_ID] PRIMARY KEY CLUSTERED 
(
	[ID_TIPONOMINA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TIPOSOLICITUD]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPOSOLICITUD](
	[ID_TIPOSOLICITUD] [bigint] IDENTITY(1,1) NOT NULL,
	[NOMBRE_TIPO_SOLICITUD] [varchar](50) NULL,
	[DESCRIPCION] [varchar](100) NULL,
 CONSTRAINT [PK_TIPOSOLICITUD_ID] PRIMARY KEY CLUSTERED 
(
	[ID_TIPOSOLICITUD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20240606044628_Inicial', N'8.0.6')
GO
INSERT [dbo].[AspNetRoles] ([Id], [Name], [NormalizedName], [ConcurrencyStamp]) VALUES (N'1', N'ADMINISTRADOR', NULL, NULL)
INSERT [dbo].[AspNetRoles] ([Id], [Name], [NormalizedName], [ConcurrencyStamp]) VALUES (N'2', N'RECURSOS HUMANOS', NULL, NULL)
INSERT [dbo].[AspNetRoles] ([Id], [Name], [NormalizedName], [ConcurrencyStamp]) VALUES (N'3', N'EMPLEADO', NULL, NULL)
GO
INSERT [dbo].[AspNetUserLogins] ([LoginProvider], [ProviderKey], [ProviderDisplayName], [UserId]) VALUES (N'Microsoft', N'c70b66ca-96a1-4238-8a83-110f1d7e46ed', N'Microsoft', N'36ba66b6-a40a-4444-8cdd-14e8b92f60c6')
GO
INSERT [dbo].[AspNetUserRoles] ([UserId], [RoleId]) VALUES (N'36ba66b6-a40a-4444-8cdd-14e8b92f60c6', N'1')
GO
INSERT [dbo].[AspNetUsers] ([Id], [UserName], [NormalizedUserName], [Email], [NormalizedEmail], [EmailConfirmed], [PasswordHash], [SecurityStamp], [ConcurrencyStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEnd], [LockoutEnabled], [AccessFailedCount]) VALUES (N'36ba66b6-a40a-4444-8cdd-14e8b92f60c6', N'tcamacho@proinsalat.com', N'TCAMACHO@PROINSALAT.COM', N'tcamacho@proinsalat.com', N'TCAMACHO@PROINSALAT.COM', 0, NULL, N'Z5YELD7SL32TKYYH655NXVMOANZFKBLD', N'73ec4b02-dd4a-4be5-b692-ad82b52b7274', NULL, 0, 0, NULL, 1, 0)
GO
SET IDENTITY_INSERT [dbo].[CARGO] ON 

INSERT [dbo].[CARGO] ([ID_CARGO], [NOMBRE_CARGO], [DESCRIPCION]) VALUES (1, N'PRUEBA_CARGO', N'PRUEBA')
INSERT [dbo].[CARGO] ([ID_CARGO], [NOMBRE_CARGO], [DESCRIPCION]) VALUES (2, N'DESARROLLADOR', N'PRUEBA')
INSERT [dbo].[CARGO] ([ID_CARGO], [NOMBRE_CARGO], [DESCRIPCION]) VALUES (3, N'ANALISTA', N'PRUEBA')
SET IDENTITY_INSERT [dbo].[CARGO] OFF
GO
SET IDENTITY_INSERT [dbo].[CORREO] ON 

INSERT [dbo].[CORREO] ([ID_CORREO], [CORREO]) VALUES (1, N'tcamacho@proinsalat.com')
INSERT [dbo].[CORREO] ([ID_CORREO], [CORREO]) VALUES (4, N'tcamacho@proinsalat.com')
INSERT [dbo].[CORREO] ([ID_CORREO], [CORREO]) VALUES (5, N'tcamacho@proinsaca.com')
INSERT [dbo].[CORREO] ([ID_CORREO], [CORREO]) VALUES (6, N'tcamacho@proinsaca.com')
SET IDENTITY_INSERT [dbo].[CORREO] OFF
GO
SET IDENTITY_INSERT [dbo].[DEPARTAMENTO] ON 

INSERT [dbo].[DEPARTAMENTO] ([ID_DEPARTAMENTO], [NOMBRE_DEPARTAMENTO], [DESCRIPCION]) VALUES (1, N'SIN DEFINIR', N'SIN DEFINIR')
INSERT [dbo].[DEPARTAMENTO] ([ID_DEPARTAMENTO], [NOMBRE_DEPARTAMENTO], [DESCRIPCION]) VALUES (2, N'CONSULTORIA', N'CONSULTORIA')
INSERT [dbo].[DEPARTAMENTO] ([ID_DEPARTAMENTO], [NOMBRE_DEPARTAMENTO], [DESCRIPCION]) VALUES (3, N'DESARROLLO', N'DESARROLLO')
INSERT [dbo].[DEPARTAMENTO] ([ID_DEPARTAMENTO], [NOMBRE_DEPARTAMENTO], [DESCRIPCION]) VALUES (4, N'SOPORTE', N'SOPORTE')
INSERT [dbo].[DEPARTAMENTO] ([ID_DEPARTAMENTO], [NOMBRE_DEPARTAMENTO], [DESCRIPCION]) VALUES (5, N'OPERACIONES', N'OPERACIONES')
INSERT [dbo].[DEPARTAMENTO] ([ID_DEPARTAMENTO], [NOMBRE_DEPARTAMENTO], [DESCRIPCION]) VALUES (6, N'RECURSOS HUMANOS', N'RECURSOS HUMANOS')
INSERT [dbo].[DEPARTAMENTO] ([ID_DEPARTAMENTO], [NOMBRE_DEPARTAMENTO], [DESCRIPCION]) VALUES (7, N'GERENCIA GENERAL', N'GERENCIA GENERAL')
SET IDENTITY_INSERT [dbo].[DEPARTAMENTO] OFF
GO
SET IDENTITY_INSERT [dbo].[DIRRECCION] ON 

INSERT [dbo].[DIRRECCION] ([ID_DIRECCION], [DIRRECION]) VALUES (1, N'cartago')
INSERT [dbo].[DIRRECCION] ([ID_DIRECCION], [DIRRECION]) VALUES (2, N'san jose')
SET IDENTITY_INSERT [dbo].[DIRRECCION] OFF
GO
SET IDENTITY_INSERT [dbo].[EMPLEADO] ON 

INSERT [dbo].[EMPLEADO] ([ID_EMPLEADO], [IDENTIFICACION], [NOMBRECOMPLETO], [FECHA_NACIMIENTO], [FECHA_INGRESO], [FOTO], [SALARIO], [SALDO_VACACIONES], [CARGO_ID], [CORREO_ID], [HORARIOLABORAL_ID], [DEPARTAMENTO_ID], [ESTADO]) VALUES (1, NULL, N'TIFFANY CAMACHO MONGE', NULL, NULL, NULL, NULL, NULL, 1, 1, NULL, 2, 1)
INSERT [dbo].[EMPLEADO] ([ID_EMPLEADO], [IDENTIFICACION], [NOMBRECOMPLETO], [FECHA_NACIMIENTO], [FECHA_INGRESO], [FOTO], [SALARIO], [SALDO_VACACIONES], [CARGO_ID], [CORREO_ID], [HORARIOLABORAL_ID], [DEPARTAMENTO_ID], [ESTADO]) VALUES (3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4, NULL, NULL, 1)
SET IDENTITY_INSERT [dbo].[EMPLEADO] OFF
GO
SET IDENTITY_INSERT [dbo].[EMPLEADODIRRECCION] ON 

INSERT [dbo].[EMPLEADODIRRECCION] ([ID_EMPLEADODIRRECCION], [EMPLEADO_ID], [DIRRECION_ID]) VALUES (1, 3, 1)
INSERT [dbo].[EMPLEADODIRRECCION] ([ID_EMPLEADODIRRECCION], [EMPLEADO_ID], [DIRRECION_ID]) VALUES (2, 3, 2)
SET IDENTITY_INSERT [dbo].[EMPLEADODIRRECCION] OFF
GO
SET IDENTITY_INSERT [dbo].[EMPLEADOTELEFONO] ON 

INSERT [dbo].[EMPLEADOTELEFONO] ([ID_EMPLEADOTELEFONO], [EMPLEADO_ID], [TELEFONO_ID]) VALUES (1, 3, 1)
INSERT [dbo].[EMPLEADOTELEFONO] ([ID_EMPLEADOTELEFONO], [EMPLEADO_ID], [TELEFONO_ID]) VALUES (2, 3, 2)
SET IDENTITY_INSERT [dbo].[EMPLEADOTELEFONO] OFF
GO
SET IDENTITY_INSERT [dbo].[HORARIOLABORAL] ON 

INSERT [dbo].[HORARIOLABORAL] ([ID_HORARIOLABORAL], [NOMBREHL], [DESCRIPCION], [HORA_INGRESO], [HORA_SALIDA]) VALUES (1, N'JORNADA ESTANDAR', N'JORNADA ESTANDAR', 8, 17)
SET IDENTITY_INSERT [dbo].[HORARIOLABORAL] OFF
GO
SET IDENTITY_INSERT [dbo].[TELEFONO] ON 

INSERT [dbo].[TELEFONO] ([ID_TELEFONO], [TELEFONO]) VALUES (1, N'61046045')
INSERT [dbo].[TELEFONO] ([ID_TELEFONO], [TELEFONO]) VALUES (2, N'61046047')
SET IDENTITY_INSERT [dbo].[TELEFONO] OFF
GO
ALTER TABLE [dbo].[APROBACIONSOLICITUD]  WITH CHECK ADD  CONSTRAINT [FK_APROBACIONSOLICITUD_EMPLEADO] FOREIGN KEY([ENCARGADO_APROBACION_ID])
REFERENCES [dbo].[EMPLEADO] ([ID_EMPLEADO])
GO
ALTER TABLE [dbo].[APROBACIONSOLICITUD] CHECK CONSTRAINT [FK_APROBACIONSOLICITUD_EMPLEADO]
GO
ALTER TABLE [dbo].[APROBACIONSOLICITUD]  WITH CHECK ADD  CONSTRAINT [FK_APROBACIONSOLICITUD_SOLICITUD] FOREIGN KEY([SOLICITUD_ID])
REFERENCES [dbo].[SOLICITUD] ([ID_SOLICITUD])
GO
ALTER TABLE [dbo].[APROBACIONSOLICITUD] CHECK CONSTRAINT [FK_APROBACIONSOLICITUD_SOLICITUD]
GO
ALTER TABLE [dbo].[AspNetRoleClaims]  WITH CHECK ADD  CONSTRAINT [FK_AspNetRoleClaims_AspNetRoles_RoleId] FOREIGN KEY([RoleId])
REFERENCES [dbo].[AspNetRoles] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AspNetRoleClaims] CHECK CONSTRAINT [FK_AspNetRoleClaims_AspNetRoles_RoleId]
GO
ALTER TABLE [dbo].[AspNetUserClaims]  WITH CHECK ADD  CONSTRAINT [FK_AspNetUserClaims_AspNetUsers_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[AspNetUsers] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AspNetUserClaims] CHECK CONSTRAINT [FK_AspNetUserClaims_AspNetUsers_UserId]
GO
ALTER TABLE [dbo].[AspNetUserLogins]  WITH CHECK ADD  CONSTRAINT [FK_AspNetUserLogins_AspNetUsers_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[AspNetUsers] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AspNetUserLogins] CHECK CONSTRAINT [FK_AspNetUserLogins_AspNetUsers_UserId]
GO
ALTER TABLE [dbo].[AspNetUserRoles]  WITH CHECK ADD  CONSTRAINT [FK_AspNetUserRoles_AspNetRoles_RoleId] FOREIGN KEY([RoleId])
REFERENCES [dbo].[AspNetRoles] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AspNetUserRoles] CHECK CONSTRAINT [FK_AspNetUserRoles_AspNetRoles_RoleId]
GO
ALTER TABLE [dbo].[AspNetUserRoles]  WITH CHECK ADD  CONSTRAINT [FK_AspNetUserRoles_AspNetUsers_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[AspNetUsers] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AspNetUserRoles] CHECK CONSTRAINT [FK_AspNetUserRoles_AspNetUsers_UserId]
GO
ALTER TABLE [dbo].[AspNetUserTokens]  WITH CHECK ADD  CONSTRAINT [FK_AspNetUserTokens_AspNetUsers_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[AspNetUsers] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AspNetUserTokens] CHECK CONSTRAINT [FK_AspNetUserTokens_AspNetUsers_UserId]
GO
ALTER TABLE [dbo].[DEDUCCIONNOMINA]  WITH CHECK ADD  CONSTRAINT [FK_DEDUCCIONNOMINA_DEDUCCION] FOREIGN KEY([DEDUCCION_ID])
REFERENCES [dbo].[DEDUCCION] ([ID_DEDUCCION])
GO
ALTER TABLE [dbo].[DEDUCCIONNOMINA] CHECK CONSTRAINT [FK_DEDUCCIONNOMINA_DEDUCCION]
GO
ALTER TABLE [dbo].[DEPARTAMENTOSUPERVISOR]  WITH CHECK ADD  CONSTRAINT [FK_DEPARTAMENTOSUPERVISOR_DEPARTAMENTO] FOREIGN KEY([DEPARTAMENTO_ID])
REFERENCES [dbo].[DEPARTAMENTO] ([ID_DEPARTAMENTO])
GO
ALTER TABLE [dbo].[DEPARTAMENTOSUPERVISOR] CHECK CONSTRAINT [FK_DEPARTAMENTOSUPERVISOR_DEPARTAMENTO]
GO
ALTER TABLE [dbo].[DEPARTAMENTOSUPERVISOR]  WITH CHECK ADD  CONSTRAINT [FK_DEPARTAMENTOSUPERVISOR_EMPLEADO] FOREIGN KEY([EMPLEADO_ID])
REFERENCES [dbo].[EMPLEADO] ([ID_EMPLEADO])
GO
ALTER TABLE [dbo].[DEPARTAMENTOSUPERVISOR] CHECK CONSTRAINT [FK_DEPARTAMENTOSUPERVISOR_EMPLEADO]
GO
ALTER TABLE [dbo].[EMPLEADO]  WITH CHECK ADD  CONSTRAINT [FK_EMPLEADO_CARGO] FOREIGN KEY([CARGO_ID])
REFERENCES [dbo].[CARGO] ([ID_CARGO])
GO
ALTER TABLE [dbo].[EMPLEADO] CHECK CONSTRAINT [FK_EMPLEADO_CARGO]
GO
ALTER TABLE [dbo].[EMPLEADO]  WITH CHECK ADD  CONSTRAINT [FK_EMPLEADO_CORREO] FOREIGN KEY([CORREO_ID])
REFERENCES [dbo].[CORREO] ([ID_CORREO])
GO
ALTER TABLE [dbo].[EMPLEADO] CHECK CONSTRAINT [FK_EMPLEADO_CORREO]
GO
ALTER TABLE [dbo].[EMPLEADO]  WITH CHECK ADD  CONSTRAINT [FK_EMPLEADO_DEPARTAMENTO] FOREIGN KEY([DEPARTAMENTO_ID])
REFERENCES [dbo].[DEPARTAMENTO] ([ID_DEPARTAMENTO])
GO
ALTER TABLE [dbo].[EMPLEADO] CHECK CONSTRAINT [FK_EMPLEADO_DEPARTAMENTO]
GO
ALTER TABLE [dbo].[EMPLEADO]  WITH CHECK ADD  CONSTRAINT [FK_EMPLEADO_HORARIOLABORAL] FOREIGN KEY([HORARIOLABORAL_ID])
REFERENCES [dbo].[HORARIOLABORAL] ([ID_HORARIOLABORAL])
GO
ALTER TABLE [dbo].[EMPLEADO] CHECK CONSTRAINT [FK_EMPLEADO_HORARIOLABORAL]
GO
ALTER TABLE [dbo].[EMPLEADOCAPACITACION]  WITH CHECK ADD  CONSTRAINT [FK_EMPLEADOCAPACITACION_CAPACITACION] FOREIGN KEY([CAPACITACION_ID])
REFERENCES [dbo].[CAPACITACION] ([ID_CAPACION])
GO
ALTER TABLE [dbo].[EMPLEADOCAPACITACION] CHECK CONSTRAINT [FK_EMPLEADOCAPACITACION_CAPACITACION]
GO
ALTER TABLE [dbo].[EMPLEADOCAPACITACION]  WITH CHECK ADD  CONSTRAINT [FK_EMPLEADOCAPACITACION_EMPLEADO] FOREIGN KEY([EMPLEADO_ID])
REFERENCES [dbo].[EMPLEADO] ([ID_EMPLEADO])
GO
ALTER TABLE [dbo].[EMPLEADOCAPACITACION] CHECK CONSTRAINT [FK_EMPLEADOCAPACITACION_EMPLEADO]
GO
ALTER TABLE [dbo].[EMPLEADODIRRECCION]  WITH CHECK ADD  CONSTRAINT [FK_EMPLEADODIRRECCION_DIRECCION] FOREIGN KEY([DIRRECION_ID])
REFERENCES [dbo].[DIRRECCION] ([ID_DIRECCION])
GO
ALTER TABLE [dbo].[EMPLEADODIRRECCION] CHECK CONSTRAINT [FK_EMPLEADODIRRECCION_DIRECCION]
GO
ALTER TABLE [dbo].[EMPLEADODIRRECCION]  WITH CHECK ADD  CONSTRAINT [FK_EMPLEADODIRRECCION_EMPLEADO] FOREIGN KEY([EMPLEADO_ID])
REFERENCES [dbo].[EMPLEADO] ([ID_EMPLEADO])
GO
ALTER TABLE [dbo].[EMPLEADODIRRECCION] CHECK CONSTRAINT [FK_EMPLEADODIRRECCION_EMPLEADO]
GO
ALTER TABLE [dbo].[EMPLEADODOCUMENTO]  WITH CHECK ADD  CONSTRAINT [FK_EMPLEADODOCUMENTO_EMPLEADO] FOREIGN KEY([EMPLEADO_ID])
REFERENCES [dbo].[EMPLEADO] ([ID_EMPLEADO])
GO
ALTER TABLE [dbo].[EMPLEADODOCUMENTO] CHECK CONSTRAINT [FK_EMPLEADODOCUMENTO_EMPLEADO]
GO
ALTER TABLE [dbo].[EMPLEADODOCUMENTO]  WITH CHECK ADD  CONSTRAINT [FK_EMPLEADODOCUMENTO_TIPODOCUMENTO] FOREIGN KEY([TIPODOCUMENTO_ID])
REFERENCES [dbo].[TIPODOCUMENTO] ([ID_TIPODOCUMENTO])
GO
ALTER TABLE [dbo].[EMPLEADODOCUMENTO] CHECK CONSTRAINT [FK_EMPLEADODOCUMENTO_TIPODOCUMENTO]
GO
ALTER TABLE [dbo].[EMPLEADOTELEFONO]  WITH CHECK ADD  CONSTRAINT [FK_EMPLEADOTELEFONO_EMPLEADO] FOREIGN KEY([EMPLEADO_ID])
REFERENCES [dbo].[EMPLEADO] ([ID_EMPLEADO])
GO
ALTER TABLE [dbo].[EMPLEADOTELEFONO] CHECK CONSTRAINT [FK_EMPLEADOTELEFONO_EMPLEADO]
GO
ALTER TABLE [dbo].[EMPLEADOTELEFONO]  WITH CHECK ADD  CONSTRAINT [FK_EMPLEADOTELEFONO_TELEFONO] FOREIGN KEY([TELEFONO_ID])
REFERENCES [dbo].[TELEFONO] ([ID_TELEFONO])
GO
ALTER TABLE [dbo].[EMPLEADOTELEFONO] CHECK CONSTRAINT [FK_EMPLEADOTELEFONO_TELEFONO]
GO
ALTER TABLE [dbo].[FLUJOAPROBACION]  WITH CHECK ADD  CONSTRAINT [FK_FLUJOAPROBACION_DEPARTAMENTO1] FOREIGN KEY([DEPARTAMENTO_APROBACION_ID])
REFERENCES [dbo].[DEPARTAMENTO] ([ID_DEPARTAMENTO])
GO
ALTER TABLE [dbo].[FLUJOAPROBACION] CHECK CONSTRAINT [FK_FLUJOAPROBACION_DEPARTAMENTO1]
GO
ALTER TABLE [dbo].[FLUJOAPROBACION]  WITH CHECK ADD  CONSTRAINT [FK_FLUJOAPROBACION_DEPARTAMENTO2] FOREIGN KEY([DEPARTAMENTO_ID])
REFERENCES [dbo].[DEPARTAMENTO] ([ID_DEPARTAMENTO])
GO
ALTER TABLE [dbo].[FLUJOAPROBACION] CHECK CONSTRAINT [FK_FLUJOAPROBACION_DEPARTAMENTO2]
GO
ALTER TABLE [dbo].[INGRESONOMINA]  WITH CHECK ADD  CONSTRAINT [FK_INGRESONOMINA_INGRESO] FOREIGN KEY([INGRESO_ID])
REFERENCES [dbo].[INGRESO] ([ID_INGRESO])
GO
ALTER TABLE [dbo].[INGRESONOMINA] CHECK CONSTRAINT [FK_INGRESONOMINA_INGRESO]
GO
ALTER TABLE [dbo].[NOMINA]  WITH CHECK ADD  CONSTRAINT [FK_NOMINA_EMPLEADO1] FOREIGN KEY([CREADOR_ID])
REFERENCES [dbo].[EMPLEADO] ([ID_EMPLEADO])
GO
ALTER TABLE [dbo].[NOMINA] CHECK CONSTRAINT [FK_NOMINA_EMPLEADO1]
GO
ALTER TABLE [dbo].[NOMINA]  WITH CHECK ADD  CONSTRAINT [FK_NOMINA_EMPLEADO2] FOREIGN KEY([APROBADOR_ID])
REFERENCES [dbo].[EMPLEADO] ([ID_EMPLEADO])
GO
ALTER TABLE [dbo].[NOMINA] CHECK CONSTRAINT [FK_NOMINA_EMPLEADO2]
GO
ALTER TABLE [dbo].[NOMINA]  WITH CHECK ADD  CONSTRAINT [FK_NOMINA_TIPONOMINA] FOREIGN KEY([TIPONOMINA_ID])
REFERENCES [dbo].[TIPONOMINA] ([ID_TIPONOMINA])
GO
ALTER TABLE [dbo].[NOMINA] CHECK CONSTRAINT [FK_NOMINA_TIPONOMINA]
GO
ALTER TABLE [dbo].[NOMINA]  WITH CHECK ADD  CONSTRAINT [FK_NOMINA_DEDUCCIONNOMINA] FOREIGN KEY([DEDUCCIONNOMINA_ID])
REFERENCES [dbo].[DEDUCCIONNOMINA] ([ID_DEDUCCIONNOMINA])
GO
ALTER TABLE [dbo].[NOMINA] CHECK CONSTRAINT [FK_NOMINA_DEDUCCIONNOMINA]
GO
ALTER TABLE [dbo].[NOMINA]  WITH CHECK ADD  CONSTRAINT [FK_NOMINA_EMPLEADO] FOREIGN KEY([EMPLEADO_ID])
REFERENCES [dbo].[EMPLEADO] ([ID_EMPLEADO])
GO
ALTER TABLE [dbo].[NOMINA] CHECK CONSTRAINT [FK_NOMINA_EMPLEADO]
GO
ALTER TABLE [dbo].[NOMINA]  WITH CHECK ADD  CONSTRAINT [FK_NOMINA_INGRESONOMINA] FOREIGN KEY([INGRESONOMINA_ID])
REFERENCES [dbo].[INGRESONOMINA] ([ID_INGRESONOMINA])
GO
ALTER TABLE [dbo].[NOMINA] CHECK CONSTRAINT [FK_NOMINA_INGRESONOMINA]
GO

ALTER TABLE [dbo].[REGISTROACTIVIDAD]  WITH CHECK ADD  CONSTRAINT [FK_REGISTROACTIVIDAD_EMPLEADO] FOREIGN KEY([EMPLEADO_ID])
REFERENCES [dbo].[EMPLEADO] ([ID_EMPLEADO])
GO
ALTER TABLE [dbo].[REGISTROACTIVIDAD] CHECK CONSTRAINT [FK_REGISTROACTIVIDAD_EMPLEADO]
GO
ALTER TABLE [dbo].[REGISTROACTIVIDAD]  WITH CHECK ADD  CONSTRAINT [FK_REGISTROACTIVIDAD_TIPOACTIVIDAD] FOREIGN KEY([TIPOACTIVIDAD_ID])
REFERENCES [dbo].[TIPOACTIVIDAD] ([ID_TIPOACTIVIDAD])
GO
ALTER TABLE [dbo].[REGISTROACTIVIDAD] CHECK CONSTRAINT [FK_REGISTROACTIVIDAD_TIPOACTIVIDAD]
GO
ALTER TABLE [dbo].[SOLICITUD]  WITH CHECK ADD  CONSTRAINT [FK_SOLICITUD_EMPLEADO] FOREIGN KEY([SOLICITANTE_ID])
REFERENCES [dbo].[EMPLEADO] ([ID_EMPLEADO])
GO
ALTER TABLE [dbo].[SOLICITUD] CHECK CONSTRAINT [FK_SOLICITUD_EMPLEADO]
GO
ALTER TABLE [dbo].[SOLICITUD]  WITH CHECK ADD  CONSTRAINT [FK_SOLICITUD_TIPOSOLICITUD] FOREIGN KEY([TIPOSOLICITUD_ID])
REFERENCES [dbo].[TIPOSOLICITUD] ([ID_TIPOSOLICITUD])
GO
ALTER TABLE [dbo].[SOLICITUD] CHECK CONSTRAINT [FK_SOLICITUD_TIPOSOLICITUD]
GO
/****** Object:  StoredProcedure [dbo].[ConsultarEmpleado]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

----PROCEDIMIENTOS
CREATE PROCEDURE [dbo].[ConsultarEmpleado]
@ID_EMPLEADO BIGINT
AS
BEGIN

	SELECT E.[IDENTIFICACION],E.[NOMBRECOMPLETO],E.[FECHA_NACIMIENTO]
		  ,E.[FECHA_INGRESO],E.[FOTO],E.[SALARIO],E.[SALDO_VACACIONES]
		  ,CA.NOMBRE_CARGO,C.CORREO,E.[HORARIOLABORAL_ID],D.NOMBRE_DEPARTAMENTO
	  FROM [dbo].[EMPLEADO] E
	  INNER JOIN CORREO C ON C.ID_CORREO = E.CORREO_ID
	  INNER JOIN DEPARTAMENTO D ON E.DEPARTAMENTO_ID = D.ID_DEPARTAMENTO
	  INNER JOIN CARGO CA ON E.CARGO_ID = CA.ID_CARGO
	  WHERE E.[ID_EMPLEADO] = @ID_EMPLEADO
END
GO
/****** Object:  StoredProcedure [dbo].[ObtenerDatosEmpleado]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/****** Object:  StoredProcedure [dbo].[ObtenerInformacionEmpleado]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE procedure [dbo].[ObtenerInformacionEmpleado]
as begin
SELECT 
    em.IDENTIFICACION,
    em.NOMBRECOMPLETO,
    em.FECHA_NACIMIENTO,
    em.FOTO,
    co.CORREO,
    roles.Name as ROL,
    de.DESCRIPCION AS DEPARTAMENTO,
    ca.NOMBRE_CARGO AS CARGO,
    ho.DESCRIPCION AS HORARIO,
    em.SALARIO,
    em.SALDO_VACACIONES,
    STRING_AGG(direc.DIRRECION, ',') AS DIRRECIONES,
	STRING_AGG(tel.TELEFONO, ', ') AS TELEFONOS,
	em.ESTADO
FROM 
    EMPLEADO em
LEFT JOIN 
    CARGO ca ON em.CARGO_ID = ca.ID_CARGO
INNER JOIN 
    CORREO co ON co.ID_CORREO = em.CORREO_ID
LEFT JOIN  
    HORARIOLABORAL ho ON ho.ID_HORARIOLABORAL = em.HORARIOLABORAL_ID
LEFT JOIN 
    DEPARTAMENTO de ON de.ID_DEPARTAMENTO = em.DEPARTAMENTO_ID
INNER JOIN 
    AspNetUsers users ON users.Email = co.CORREO
INNER JOIN 
    AspNetUserRoles userol ON userol.UserId = users.Id
INNER JOIN 
    AspNetRoles roles ON roles.Id = userol.RoleId
LEFT JOIN 
    EMPLEADODIRRECCION empledirec ON empledirec.EMPLEADO_ID = em.ID_EMPLEADO
LEFT JOIN 
    DIRRECCION direc ON direc.ID_DIRECCION = empledirec.DIRRECION_ID

	LEFT JOIN EMPLEADOTELEFONO empletel on empletel.EMPLEADO_ID=em.ID_EMPLEADO

	LEFT join TELEFONO tel on tel.ID_TELEFONO=empletel.TELEFONO_ID
GROUP BY 
    em.IDENTIFICACION,
    em.NOMBRECOMPLETO,
    em.FECHA_NACIMIENTO,
    em.FOTO,
    co.CORREO,
    roles.Name,
    de.DESCRIPCION,
    ca.NOMBRE_CARGO,
    ho.DESCRIPCION,
    em.SALARIO,
    em.SALDO_VACACIONES,
	em.ESTADO
	END
GO
/****** Object:  Trigger [dbo].[trg_AfterInsert_AspNetUsers]    Script Date: 6/10/2024 9:05:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
---TRIGGER
CREATE TRIGGER [dbo].[trg_AfterInsert_AspNetUsers]
ON [dbo].[AspNetUsers]
AFTER INSERT
AS
BEGIN
BEGIN TRY
    -- Validar si el correo existe
    IF NOT EXISTS (
        SELECT 1
        FROM CORREO C
        INNER JOIN INSERTED I ON C.CORREO = I.Email
    )
    BEGIN
        -- Insertar el correo en la tabla CORREO solo si no existe
        INSERT INTO CORREO (CORREO)
        SELECT DISTINCT Email 
        FROM INSERTED 
        -- Insertar en la tabla EMPLEADO con el CORREO_ID correspondiente al correo.
        INSERT INTO EMPLEADO (CORREO_ID, ESTADO)
        SELECT C.ID_CORREO,1
        FROM CORREO C
        INNER JOIN INSERTED I ON C.CORREO = I.Email
        -- Insertar en la tabla AspNetUserRoles con el ROL 1(Empleado)
        INSERT INTO AspNetUserRoles (UserId, RoleId)
        SELECT I.Id, 1
        FROM INSERTED I;
    END
END TRY
BEGIN CATCH
    INSERT INTO [dbo].[DB_ERRORES]
           ([UserName]
           ,[ErrorNumber]
           ,[ErrorState]
           ,[ErrorSeverity]
           ,[ErrorLine]
           ,[ErrorProcedure]
           ,[ErrorMessage]
           ,[ErrorDateTime])
    VALUES
    (SUSER_SNAME(),
    ERROR_NUMBER(),
    ERROR_STATE(),
    ERROR_SEVERITY(),
    ERROR_LINE(),
    ERROR_PROCEDURE(),
    ERROR_MESSAGE(),
    GETDATE());
END CATCH
END;

GO
ALTER TABLE [dbo].[AspNetUsers] ENABLE TRIGGER [trg_AfterInsert_AspNetUsers]
GO

ALTER PROCEDURE [dbo].[ConsultarEmpleado] 
@CORREO varchar(100) 
AS
BEGIN

	SELECT E.[IDENTIFICACION],E.[NOMBRECOMPLETO],E.[FECHA_NACIMIENTO]
		  ,E.[FECHA_INGRESO],E.[FOTO],E.[SALARIO],E.[SALDO_VACACIONES]
		  ,CA.NOMBRE_CARGO,C.CORREO,E.[HORARIOLABORAL_ID],D.NOMBRE_DEPARTAMENTO,
		  T.TELEFONO,
		  DI.DIRRECION
	  FROM [dbo].[EMPLEADO] E
	  INNER JOIN CORREO C ON C.ID_CORREO = E.CORREO_ID
	  INNER JOIN DEPARTAMENTO D ON E.DEPARTAMENTO_ID = D.ID_DEPARTAMENTO
	  INNER JOIN CARGO CA ON E.CARGO_ID = CA.ID_CARGO
	  INNER JOIN EMPLEADOTELEFONO ET ON ET.EMPLEADO_ID=E.ID_EMPLEADO
	  INNER JOIN TELEFONO T ON T.ID_TELEFONO=ET.TELEFONO_ID
	  INNER JOIN EMPLEADODIRRECCION ED ON ED.EMPLEADO_ID=E.ID_EMPLEADO
	  INNER JOIN DIRRECCION DI ON DI.ID_DIRECCION=ED.DIRRECION_ID
	 
	 
	  WHERE C.CORREO=@CORREO
END

----CAMBIOS 17 DE JUNIO-----

  ALTER TABLE APROBACIONSOLICITUD ALTER COLUMN FECHA_APROBACIONSOLICITUD datetime null
  go

  CREATE FUNCTION [dbo].[CalcularDias] (
    @INICIO DATE,
    @FIN DATE
)
RETURNS INT
AS
BEGIN
    DECLARE @BusinessDays INT;

    WITH FECHASRANGO AS (
        SELECT @INICIO AS DateValue
        UNION ALL
        SELECT DATEADD(DAY, 1, DateValue)
        FROM FECHASRANGO 
        WHERE DateValue < @FIN
    )
    SELECT @BusinessDays = COUNT(*)
    FROM FECHASRANGO 
    WHERE DateValue >= @INICIO AND DateValue <= @FIN -- Dentro del rango de fechas
        AND DATEPART(WEEKDAY, DateValue) NOT IN (1, 7); -- Excluye domingos (1) y sábados (7)

    RETURN @BusinessDays;
END;
go

create PROCEDURE [dbo].[RegistrarSolicitud]
  @FECHA_INICIO datetime,
  @FECHA_FINAL datetime,
  @COMENTARIO varchar(max),
  @DETALLE varchar(max),
  @SOLICITANTE_ID bigint,
  @TIPOSOLICITUD_ID bigint
AS
BEGIN

  BEGIN TRY
  DECLARE @ID_SOLICITUD BIGINT

  IF (@TIPOSOLICITUD_ID IN (1, 2, 5))
  BEGIN
  DECLARE @DIAS INT
  DECLARE @SALDO_DISPONIBLE BIGINT
SET @DIAS=[dbo].[CalcularDias](@FECHA_INICIO,@FECHA_FINAL);
SET @SALDO_DISPONIBLE=( SELECT SALDO_VACACIONES FROM EMPLEADO WHERE ID_EMPLEADO=@SOLICITANTE_ID)

IF(@SALDO_DISPONIBLE>=@DIAS)
BEGIN
    -- Insert the new solicitud record
    INSERT INTO SOLICITUD (
        FECHA_SOLICITUD,
        FECHA_INICIO,
        FECHA_FINAL,
        COMENTARIO,
        DIAS,
        DETALLE,
        ESTADO_SOLICITUD,
        SOLICITANTE_ID,
        TIPOSOLICITUD_ID
    ) VALUES (
        GETDATE(),
        @FECHA_INICIO,
        @FECHA_FINAL,
        @COMENTARIO,
        @DIAS,
        @DETALLE,
        'P',
        @SOLICITANTE_ID,
        @TIPOSOLICITUD_ID
    );
  END
  SET @ID_SOLICITUD=SCOPE_IDENTITY()
  exec [dbo].[RegistrarAprobaciones] @ID_SOLICITUD
  END
  ELSE
  BEGIN
 
    PRINT 'El tipo de solicitud ';
  END
END TRY
BEGIN CATCH
  INSERT INTO [dbo].[DB_ERRORES]
           ([UserName]
           ,[ErrorNumber]
           ,[ErrorState]
           ,[ErrorSeverity]
           ,[ErrorLine]
           ,[ErrorProcedure]
           ,[ErrorMessage]
           ,[ErrorDateTime])

    VALUES
  (SUSER_SNAME(),
   ERROR_NUMBER(),
   ERROR_STATE(),
   ERROR_SEVERITY(),
   ERROR_LINE(),
   ERROR_PROCEDURE(),
   ERROR_MESSAGE(),
   GETDATE());
END CATCH;
END
go

create PROCEDURE [dbo].[NotificacionSolicitud]

@id_solicitud VARCHAR(50)
AS
BEGIN TRY
	SET NOCOUNT ON;	

	DECLARE	@Titule NVARCHAR(MAX),
			@Head NVARCHAR(MAX),
		    @Body NVARCHAR(MAX),
	        @MENSAJE_SOLICITUD NVARCHAR(MAX),
			@tipo_solicitud  VARCHAR(MAX),
			@Email_Usuario VARCHAR(MAX),
			@Descripcion_movimiento VARCHAR(MAX),
			@fecha_solicitud VARCHAR(MAX),
			@responsable_solicitud VARCHAR(MAX),
			@comentario_movimiento VARCHAR(MAX),
			@usuario_creador_solicitud VARCHAR(MAX),
			@Email_Usuario_aprobar VARCHAR(MAX),
			@footer VARCHAR(MAX)		

	DECLARE @Resultado INT,
			
			@TablePermiso   nvarchar(max),
			@TableAprobacion nvarchar(max),
		    @EncabezadoAprobacion  nvarchar(max),
			@INICIO_CORREO NVARCHAR(MAX),
		    @Encabezado_Correo NVARCHAR(MAX),
			@Alerta_Solicitud NVARCHAR(MAX),
			@Alerta_Aprobacion NVARCHAR(MAX),
			@MENSAJE_APROBACION  NVARCHAR(MAX),
			@APROBACION  NVARCHAR(MAX)
			
	
	

	SET @tipo_solicitud = (select tipo.NOMBRE_TIPO_SOLICITUD  from SOLICITUD soli
  inner join TIPOSOLICITUD tipo
  on soli.TIPOSOLICITUD_ID=tipo.ID_TIPOSOLICITUD
  where soli.ID_SOLICITUD=6)
	
	
	SET @fecha_solicitud = ( select  FECHA_SOLICITUD from SOLICITUD
   where ID_SOLICITUD= @id_solicitud )
	
    SET @Email_Usuario = ( select co.CORREO from SOLICITUD soli
   inner join empleado emple on emple.ID_EMPLEADO=soli.SOLICITANTE_ID
   inner join CORREO  co on co.ID_CORREO=emple.CORREO_ID
   where soli.ID_SOLICITUD=@id_solicitud)
	SET @responsable_solicitud = ( select emple.NOMBRECOMPLETO from SOLICITUD soli
   inner join empleado emple on emple.ID_EMPLEADO=soli.SOLICITANTE_ID
   where soli.ID_SOLICITUD=@id_solicitud)

   set @Email_Usuario_aprobar=(select  co.CORREO from APROBACIONSOLICITUD apsoli

inner join EMPLEADO emple on apsoli.ENCARGADO_APROBACION_ID=emple.ID_EMPLEADO
inner join CORREO co on co.ID_CORREO=emple.CORREO_ID

where apsoli.SOLICITUD_ID=@id_solicitud and apsoli.SECUENCIA=1)
	
	
	
	SET @INICIO_CORREO = 
		'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
		<html xmlns="http://www.w3.org/1999/xhtml" xmlns:o="urn:schemas-microsoft-com:office:office" style="width:100%;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;padding:0;Margin:0">

		<head>
			<meta charset="UTF-8">
			<meta content="width=device-width, initial-scale=1" name="viewport">
			<meta name="x-apple-disable-message-reformatting">
			<meta http-equiv="X-UA-Compatible" content="IE=edge">
			<meta content="telephone=no" name="format-detection">
			<title>AMS</title>

			<style type="text/css">
				#outlook a {
					padding: 0;
				}
        
				.ExternalClass {
					width: 100%;
				}
        
				.ExternalClass,
				.ExternalClass p,
				.ExternalClass span,
				.ExternalClass font,
				.ExternalClass td,
				.ExternalClass div {
					line-height: 100%;
				}
        
				.es-button {
					mso-style-priority: 100!important;
					text-decoration: none!important;
				}
        
				a[x-apple-data-detectors] {
					color: inherit!important;
					text-decoration: none!important;
					font-size: inherit!important;
					font-family: inherit!important;
					font-weight: inherit!important;
					line-height: inherit!important;
				}
        
				.es-desk-hidden {
					display: none;
					float: left;
					overflow: hidden;
					width: 0;
					max-height: 0;
					line-height: 0;
					mso-hide: all;
				}
        
				[data-ogsb] .es-button {
					border-width: 0!important;
					padding: 10px 20px 10px 20px!important;
				}
        
				@media only screen and (max-width:600px) {
					p,
					ul li,
					ol li,
					a {
						line-height: 150%!important
					}
					h1,
					h2,
					h3,
					h1 a,
					h2 a,
					h3 a {
						line-height: 120%!important
					}
					h1 {
						font-size: 30px!important;
						text-align: center
					}
					h2 {
						font-size: 26px!important;
						text-align: center
					}
					h3 {
						font-size: 20px!important;
						text-align: center
					}
					.es-header-body h1 a,
					.es-content-body h1 a,
					.es-footer-body h1 a {
						font-size: 30px!important
					}
					.es-header-body h2 a,
					.es-content-body h2 a,
					.es-footer-body h2 a {
						font-size: 26px!important
					}
					.es-header-body h3 a,
					.es-content-body h3 a,
					.es-footer-body h3 a {
						font-size: 20px!important
					}
					.es-menu td a {
						font-size: 16px!important
					}
					.es-header-body p,
					.es-header-body ul li,
					.es-header-body ol li,
					.es-header-body a {
						font-size: 16px!important
					}
					.es-content-body p,
					.es-content-body ul li,
					.es-content-body ol li,
					.es-content-body a {
						font-size: 16px!important
					}
					.es-footer-body p,
					.es-footer-body ul li,
					.es-footer-body ol li,
					.es-footer-body a {
						font-size: 16px!important
					}
					.es-infoblock p,
					.es-infoblock ul li,
					.es-infoblock ol li,
					.es-infoblock a {
						font-size: 12px!important
					}
					*[class="gmail-fix"] {
						display: none!important
					}
					.es-m-txt-c,
					.es-m-txt-c h1,
					.es-m-txt-c h2,
					.es-m-txt-c h3 {
						text-align: center!important
					}
					.es-m-txt-r,
					.es-m-txt-r h1,
					.es-m-txt-r h2,
					.es-m-txt-r h3 {
						text-align: right!important
					}
					.es-m-txt-l,
					.es-m-txt-l h1,
					.es-m-txt-l h2,
					.es-m-txt-l h3 {
						text-align: left!important
					}
					.es-m-txt-r img,
					.es-m-txt-c img,
					.es-m-txt-l img {
						display: inline!important
					}
					.es-button-border {
						display: block!important
					}
					a.es-button,
					button.es-button {
						font-size: 20px!important;
						display: block!important;
						border-width: 10px 0px 10px 0px!important
					}
					.es-btn-fw {
						border-width: 10px 0px!important;
						text-align: center!important
					}
					.es-adaptive table,
					.es-btn-fw,
					.es-btn-fw-brdr,
					.es-left,
					.es-right {
						width: 100%!important
					}
					.es-content table,
					.es-header table,
					.es-footer table,
					.es-content,
					.es-footer,
					.es-header {
						width: 100%!important;
						max-width: 600px!important
					}
					.es-adapt-td {
						display: block!important;
						width: 100%!important
					}
					.adapt-img {
						width: 100%!important;
						height: auto!important
					}
					.es-m-p0 {
						padding: 0px!important
					}
					.es-m-p0r {
						padding-right: 0px!important
					}
					.es-m-p0l {
						padding-left: 0px!important
					}
					.es-m-p0t {
						padding-top: 0px!important
					}
					.es-m-p0b {
						padding-bottom: 0!important
					}
					.es-m-p20b {
						padding-bottom: 20px!important
					}
					.es-mobile-hidden,
					.es-hidden {
						display: none!important
					}
					tr.es-desk-hidden,
					td.es-desk-hidden,
					table.es-desk-hidden {
						width: auto!important;
						overflow: visible!important;
						float: none!important;
						max-height: inherit!important;
						line-height: inherit!important
					}
					tr.es-desk-hidden {
						display: table-row!important
					}
					table.es-desk-hidden {
						display: table!important
					}
					td.es-desk-menu-hidden {
						display: table-cell!important
					}
					.es-menu td {
						width: 1%!important
					}
					table.es-table-not-adapt,
					.esd-block-html table {
						width: auto!important
					}
					table.es-social {
						display: inline-block!important
					}
					table.es-social td {
						display: inline-block!important
					}
					.es-desk-hidden {
						display: table-row!important;
						width: auto!important;
						overflow: visible!important;
						max-height: inherit!important
					}
					.h-auto {
						height: auto!important
					}
				}
			</style>
		</head>

		<body style="width:100%;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;font-family:arial, ''helvetica neue'', helvetica, sans-serif;padding:0;Margin:0">
			<div class="es-wrapper-color" style="background-color:#E4E5E7">
				<table class="es-wrapper" width="100%" cellspacing="0" cellpadding="0" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;padding:0;Margin:0;width:100%;height:100%;background-repeat:repeat;background-position:center top;background-color:#E4E5E7">
					<tr style="border-collapse:collapse">
						<td valign="top" style="padding:0;Margin:0">
							<table class="es-header" cellspacing="0" cellpadding="0" align="center" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%;background-color:transparent;background-repeat:repeat;background-position:center top">
								<tr style="border-collapse:collapse">
									<td align="center" style="padding:0;Margin:0">
										<table class="es-header-body" cellspacing="0" cellpadding="0" align="center" bgcolor="#094293" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#094293;width:600px">
											<tr style="border-collapse:collapse">
												<td align="left" style="padding:0;Margin:0;padding-top:20px;padding-left:20px;padding-right:20px">
													<table class="es-left" cellspacing="0" cellpadding="0" align="left" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left">
														<tr style="border-collapse:collapse">
															<td class="es-m-p0r es-m-p20b" valign="top" align="center" style="padding:0;Margin:0;width:178px">
																
															</td>
														</tr>
													</table>
													<table cellspacing="0" cellpadding="0" align="right" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
														<tr style="border-collapse:collapse">
															<td align="left" style="padding:0;Margin:0;width:362px">
																<table width="100%" cellspacing="0" cellpadding="0" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
																	<tr style="border-collapse:collapse">
																		<td class="es-m-txt-c" align="right" style="padding:0;Margin:0;padding-top:15px;padding-bottom:20px">
																			<p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:arial, ''helvetica neue'', helvetica, sans-serif;line-height:21px;color:#FFFFFF;font-size:14px">'+@fecha_solicitud+'</p>
																		</td>
																	</tr>
																</table>
															</td>
														</tr>
													</table>
												</td>
											</tr>
											<tr style="border-collapse:collapse">
												<td align="left" style="padding:0;Margin:0">
													<table width="100%" cellspacing="0" cellpadding="0" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
														<tr style="border-collapse:collapse">
															<td valign="top" align="center" style="padding:0;Margin:0;width:600px">
																
															</td>
														</tr>
													</table>
												</td>
											</tr>
										</table>
									</td>
								</tr>
							</table>'

	SET @Alerta_Solicitud = 
		'<table class="es-content" cellspacing="0" cellpadding="0" align="center" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%">
			<tr style="border-collapse:collapse">
				<td align="center" style="padding:0;Margin:0">
					<table class="es-content-body" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#ededed;width:600px" cellspacing="0" cellpadding="0" bgcolor="#ededed" align="center">
						<tr style="border-collapse:collapse">
							<td align="left" style="padding:0;Margin:0">
								<table width="100%" cellspacing="0" cellpadding="0" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
									<tr style="border-collapse:collapse">
										<td valign="top" align="center" style="padding:0;Margin:0;width:600px">
											<table width="100%" cellspacing="0" cellpadding="0" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
												<tr style="border-collapse:collapse">
													<td align="center" style="padding:0;Margin:0;padding-top:20px;padding-left:40px;padding-right:40px">
														<h1 style="Margin:0;line-height:31px;mso-line-height-rule:exactly;font-family:tahoma, verdana, segoe, sans-serif;font-size:26px;font-style:normal;font-weight:normal;color:#333333">Detalles Solicitud</h1>
														<p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:arial, ''helvetica neue'', helvetica, sans-serif;line-height:21px;color:#333333;font-size:14px"><br></p>
													</td>
												</tr>
												
												
												
											</table>
										</td>
									</tr>
								</table>
							</td>
						</tr>
						<tr style="border-collapse:collapse">
							<td align="left" style="padding:0;Margin:0">
								<table width="100%" cellspacing="0" cellpadding="0" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
									<tr style="border-collapse:collapse">
										<td valign="top" align="center" style="padding:0;Margin:0;width:600px">
											
										</td>
									</tr>
								</table>
							</td>
						</tr>
					</table>
				</td>
			</tr>
		</table>'

	SET @Encabezado_Correo = 
				'<table class="es-content" cellspacing="0" cellpadding="0" align="center" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%">
					<tr style="border-collapse:collapse">
						<td align="center" style="padding:0;Margin:0">
							<table class="es-content-body" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#ffffff;width:600px" cellspacing="0" cellpadding="0" bgcolor="#ffffff" align="center">
								<tr style="border-collapse:collapse">
									<td align="left" style="padding:0;Margin:0;padding-top:15px;padding-left:20px;padding-right:20px">
										<table width="100%" cellspacing="0" cellpadding="0" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
											<tr style="border-collapse:collapse">
												<td valign="top" align="center" style="padding:0;Margin:0;width:560px">
													
												</td>
											</tr>
										</table>
									</td>
								</tr>
								<tr style="border-collapse:collapse">
									<td align="left" style="Margin:0;padding-top:20px;padding-left:20px;padding-right:20px;padding-bottom:25px">
										<table cellspacing="0" cellpadding="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
											<tr style="border-collapse:collapse">
												<td align="left" style="padding:0;Margin:0;width:560px">
													<table width="100%" cellspacing="0" cellpadding="0" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
														
														<tr style="border-collapse:collapse">
															<td align="left" class="h-auto" height="30" style="padding:0;Margin:0">
																<p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:arial, ''helvetica neue'', helvetica, sans-serif;line-height:21px;color:#333333;font-size:14px"><strong>Número de solicitud: </strong> '+ @id_solicitud +'</p>
															</td>
														</tr>
														<tr style="border-collapse:collapse">
															<td align="left" class="h-auto" height="30" style="padding:0;Margin:0">
																<p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:arial, ''helvetica neue'', helvetica, sans-serif;line-height:21px;color:#333333;font-size:14px"><strong>Fecha solicitud : </strong> '+ @fecha_solicitud +'</p>
															</td>
														</tr>
														<tr style="border-collapse:collapse">
															<td align="left" class="h-auto" height="30" style="padding:0;Margin:0">
																<p style="Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:arial, ''helvetica neue'', helvetica, sans-serif;line-height:21px;color:#333333;font-size:14px"><strong>Responsable de la solicitud: </strong> '+@responsable_solicitud+'</p>
															</td>
														</tr>

													</table>
												</td>
											</tr>
										</table>
									</td>
								</tr>
								<tr style="border-collapse:collapse">
									<td style="padding:0;Margin:0;background-color:#ededed" bgcolor="#ededed" align="left">
										<table width="100%" cellspacing="0" cellpadding="0" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
											<tr style="border-collapse:collapse">
												<td valign="top" align="center" style="padding:0;Margin:0;width:600px">
													
												</td>
											</tr>
										</table>
									</td>
								</tr>
							</table>
						</td>
					</tr>
				</table>
				<table class="es-content" cellspacing="0" cellpadding="0" align="center" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%">
					<tr style="border-collapse:collapse">
						<td align="center" style="padding:0;Margin:0">
							<table class="es-content-body" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#ededed;width:600px" cellspacing="0" cellpadding="0" bgcolor="#ededed" align="center">
								<tr style="border-collapse:collapse">
									<td align="left" style="Margin:0;padding-top:20px;padding-bottom:20px;padding-left:40px;padding-right:40px">
										<table width="100%" cellspacing="0" cellpadding="0" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
											<tr style="border-collapse:collapse">
												<td align="left" style="padding:0;Margin:0;width:520px">
													<table width="100%" cellspacing="0" cellpadding="0" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
														<tr style="border-collapse:collapse">
															<td class="h-auto" align="center" height="30" style="padding:0;Margin:0">
																<h3 style="Margin:0;line-height:24px;mso-line-height-rule:exactly;font-family:tahoma, verdana, segoe, sans-serif;font-size:20px;font-style:normal;font-weight:normal;color:#333333">Datos del Permiso:</h3>
															</td>
														</tr>
														<tr style="border-collapse:collapse">
															<td style="padding:0;Margin:0">
																<table style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
																	<tr style="border-collapse:collapse">
																		<th></th>
																	</tr>
																</table>
															</td>
														</tr>
														<tr style="border-collapse:collapse">
															<td align="center" style="padding:0;Margin:0;padding-top:10px;padding-bottom:10px">
																<table border="1" align="center" cellspacing="1" cellpadding="3" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;height:70px;width:500px" class="es-table">
																	<thead>
																		<tr style="border-collapse:collapse">
																			<th style="font-size:12px;text-align:center" scope="col">Permiso</th>
																			<th style="font-size:12px;text-align:center" scope="col">Fecha Inicio</th>
					  													    <th style="font-size:12px;text-align:center" scope="col">Fecha Final</th>
																			<th style="font-size:12px;text-align:center" scope="col">Dias</th>
																			<th style="font-size:12px;text-align:center" scope="col">Tipo Permiso</th>
																			<th style="font-size:12px;text-align:center" scope="col">Comentario</th>
																		</tr>
																	</thead>
																	<tr style="border-collapse:collapse">' 
	
	

	

	SET @TablePermiso = 
	(	 select soli.ID_SOLICITUD AS [TD]	,  CONVERT(VARCHAR, soli.FECHA_INICIO, 103) AS [TD]	, convert (VARCHAR,  soli.FECHA_FINAL, 103) AS [TD]	,
   soli.DIAS AS [TD]	 ,  tipo.DESCRIPCION AS [TD]	 , soli.COMENTARIO AS [TD]	 from SOLICITUD soli
  inner join TIPOSOLICITUD tipo
  on soli.TIPOSOLICITUD_ID=tipo.ID_TIPOSOLICITUD
  where soli.ID_SOLICITUD=@id_solicitud
		FOR XML RAW('tr'), ELEMENTS) + ' 
														</tr>
													</table>
												</td>
											</tr>
											<tr style="border-collapse:collapse">
												<td class="h-auto" align="center" height="30" style="padding:0;Margin:0">
													<h3 style="Margin:0;line-height:24px;mso-line-height-rule:exactly;font-family:tahoma, verdana, segoe, sans-serif;font-size:20px;font-style:normal;font-weight:normal;color:#333333"><br></h3>
												</td>
											</tr>
										</table>
									</td>
								</tr>
							</table>
						</td>
					</tr>
				</table>
			</td>
		</tr>
	</table>' 

	
											
	SET @EncabezadoAprobacion = 
	'<table class="es-content" cellspacing="0" cellpadding="0" align="center" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%">
		<tr style="border-collapse:collapse">
			<td align="center" style="padding:0;Margin:0">
				<table class="es-content-body" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#ededed;width:600px" cellspacing="0" cellpadding="0" bgcolor="#ededed" align="center">
					<tr style="border-collapse:collapse">
						<td align="left" style="Margin:0;padding-top:20px;padding-bottom:20px;padding-left:40px;padding-right:40px">
							<table width="100%" cellspacing="0" cellpadding="0" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
								<tr style="border-collapse:collapse">
									<td align="left" style="padding:0;Margin:0;width:520px">
										<table width="100%" cellspacing="0" cellpadding="0" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
											<tr style="border-collapse:collapse">
												<td class="h-auto" align="center" height="30" style="padding:0;Margin:0">
													<h3 style="Margin:0;line-height:24px;mso-line-height-rule:exactly;font-family:tahoma, verdana, segoe, sans-serif;font-size:20px;font-style:normal;font-weight:normal;color:#333333">Aprobaciones:</h3>
												</td>
											</tr>
											<tr style="border-collapse:collapse">
												<td style="padding:0;Margin:0">
													<table style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
														<tr style="border-collapse:collapse">
															<th></th>
														</tr>
													</table>
												</td>
											</tr>
											<tr style="border-collapse:collapse">
												<td align="center" style="padding:0;Margin:0;padding-top:10px;padding-bottom:10px">
													<table border="1" align="center" cellspacing="1" cellpadding="3" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;height:70px;width:500px" class="es-table">
														<thead>
															<tr style="border-collapse:collapse">
																<th style="font-size:12px;text-align:center;color:#000000" scope="col">Departamento</th>
																<th style="font-size:12px;text-align:center;color:#000000" scope="col">Encargado</th>
																<th style="font-size:12px;text-align:center;color:#000000" scope="col">Secuencia</th>
																<th style="font-size:12px;text-align:center;color:#000000" scope="col">Estado</th>
															</tr>
														</thead>
														<tr style="border-collapse:collapse">'

	SET @TableAprobacion = 
		(SELECT DEPAP.DESCRIPCION AS [TD] ,EMPLE.NOMBRECOMPLETO AS [TD], APSOLI.SECUENCIA AS [TD],   CASE APSOLI.RESPUESTA_SOLICITUD
When 'P' Then 'PENDIENTE'
When 'A' Then 'APROBADO'
ELSE 'RECHAZADO' 
END  AS [TD] FROM APROBACIONSOLICITUD APSOLI
INNER JOIN EMPLEADO EMPLE ON APSOLI.ENCARGADO_APROBACION_ID=EMPLE.ID_EMPLEADO
INNER JOIN DEPARTAMENTOSUPERVISOR DEPASUP ON DEPASUP.EMPLEADO_ID=EMPLE.ID_EMPLEADO
INNER JOIN DEPARTAMENTO DEPAP ON DEPAP.ID_DEPARTAMENTO=DEPASUP.DEPARTAMENTO_ID

WHERE APSOLI.SOLICITUD_ID=@id_solicitud																									   
		FOR XML RAW('tr'), ELEMENTS) + '
														</tr>
													</table>
												</td>
											</tr>
											<tr style="border-collapse:collapse">
												<td class="h-auto" align="center" height="30" style="padding:0;Margin:0">
													<h3 style="Margin:0;line-height:24px;mso-line-height-rule:exactly;font-family:tahoma, verdana, segoe, sans-serif;font-size:20px;font-style:normal;font-weight:normal;color:#333333"><br></h3>
												</td>
											</tr>
										</table>
									</td>
								</tr>
							</table>
						</td>
					</tr>
				</table>
			</td>
		</tr>
	</table>'


	SET @APROBACION = '
						<tr>
                          <td>
                            <table cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
                              <tr>
                                <td align="center" valign="top" style="padding:0;Margin:0;width:560px">
                                  <table cellpadding="0" cellspacing="0" width="100%" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
                                    <tr>
                                      <td align="center" style="padding:0;Margin:0;padding-top:15px;padding-bottom:15px">
                                        <span class="es-button-border" style="border-style:solid;color:#FFFFFF;border-color:#094293;background:#094293;border-width:4px;display:inline-block;border-radius:10px;width:auto">
										  
                                            Ingrese al módulo Gestión de Personal a consultar los detalles del registro del permiso
											
									    </span>
									  </td>
                                    </tr>
                                  </table>
                                </td>
                              </tr>
                            </table>
                          </td>
                        </tr>
                      </table>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
					'

	SET @footer = 
		'<table class="es-content" cellspacing="0" cellpadding="0" align="center" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%">
			<tr style="border-collapse:collapse">
				<td align="center" style="padding:0;Margin:0">
					<table class="es-content-body" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#ededed;width:600px" cellspacing="0" cellpadding="0" bgcolor="#ededed" align="center">
						<tr style="border-collapse:collapse">
							<td align="left" style="padding:0;Margin:0">
								<table width="100%" cellspacing="0" cellpadding="0" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
									<tr style="border-collapse:collapse">
										<td valign="top" align="center" style="padding:0;Margin:0;width:600px">
											
										</td>
									</tr>
								</table>
							</td>
						</tr>
					</table>
				</td>
			</tr>
		</table>
		<table cellpadding="0" cellspacing="0" class="es-footer" align="center" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%;background-color:transparent;background-repeat:repeat;background-position:center top">
			<tr style="border-collapse:collapse">
				<td align="center" style="padding:0;Margin:0">
					<table class="es-footer-body" cellspacing="0" cellpadding="0" align="center" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:transparent;width:600px">
						<tr style="border-collapse:collapse">
							<td align="left" bgcolor="#094293" style="padding:0;Margin:0;padding-top:20px;padding-left:20px;padding-right:20px;background-color:#094293">
								<table width="100%" cellspacing="0" cellpadding="0" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
									<tr style="border-collapse:collapse">
										<td valign="top" align="center" style="padding:0;Margin:0;width:560px">
											<table width="100%" cellspacing="0" cellpadding="0" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px">
												<tr style="border-collapse:collapse">
												</tr>
											</table>
										</td>
									</tr>
								</table>
							</td>
						</tr>
					</table>
				</td>
			</tr>
		</table>
						</td>
					</tr>
				</table>
			</div>
		</body>
	</html> '


	
		SET  @MENSAJE_SOLICITUD =	@INICIO_CORREO			+ @Alerta_Solicitud			+ @Encabezado_Correo	+
								   @TablePermiso 	+  @EncabezadoAprobacion	+ @TableAprobacion		+ @footer
	
	    SET  @MENSAJE_APROBACION=	@INICIO_CORREO			+ @Alerta_Solicitud			+ @Encabezado_Correo	+
								   @TablePermiso 	+  @EncabezadoAprobacion	+ @TableAprobacion		+@APROBACION+ @footer
 
	
		IF @Email_Usuario <> ''
			BEGIN
				EXEC msdb.dbo.sp_send_dbmail
					@profile_name = 'EnvioMail',
					@recipients =  @Email_Usuario,
					@subject = 'NOTIFICACION-REGISTRO DE PERMISO',
					@body =  @MENSAJE_SOLICITUD,
					@body_format = 'HTML';
			END

			IF @Email_Usuario <> ''
			BEGIN
				EXEC msdb.dbo.sp_send_dbmail
					@profile_name = 'EnvioMail',
					@recipients =  @Email_Usuario_aprobar,
					@subject = 'REGISTRO DE PERMISO PARA APROBACION',
					@body =  @MENSAJE_APROBACION,
					@body_format = 'HTML';
			END

	select @responsable_solicitud
	select @MENSAJE_SOLICITUD
	select @Email_Usuario

			SET @Resultado = 1
END TRY
BEGIN CATCH
	
  INSERT INTO [dbo].[DB_ERRORES]
           ([UserName]
           ,[ErrorNumber]
           ,[ErrorState]
           ,[ErrorSeverity]
           ,[ErrorLine]
           ,[ErrorProcedure]
           ,[ErrorMessage]
           ,[ErrorDateTime])

    VALUES
  (SUSER_SNAME(),
   ERROR_NUMBER(),
   ERROR_STATE(),
   ERROR_SEVERITY(),
   ERROR_LINE(),
   ERROR_PROCEDURE(),
   ERROR_MESSAGE(),
   GETDATE());
END CATCH

go
create PROCEDURE [dbo].[RegistrarAprobaciones] 
    @ID_SOLICITUD bigint
AS 
BEGIN
    -- Declaración de variables
    DECLARE @ENCARGADO_APROBACION bigint;
    DECLARE @SECUENCIA varchar(200);
    DECLARE @RESPUESTA_SOLICITUD varchar(1) = 'P'; 

    BEGIN TRY
        -- Declaración del cursor
        DECLARE cursorAprobaciones CURSOR FOR
        SELECT d.SECUENCIA, e.EMPLEADO_ID
        FROM [dbo].[SOLICITUD] a 
        INNER JOIN [dbo].[EMPLEADO] b ON a.SOLICITANTE_ID = b.ID_EMPLEADO
        INNER JOIN DEPARTAMENTO c ON c.ID_DEPARTAMENTO = b.DEPARTAMENTO_ID
        INNER JOIN FLUJOAPROBACION d ON d.DEPARTAMENTO_APROBACION_ID = c.ID_DEPARTAMENTO
        INNER JOIN [dbo].[DEPARTAMENTOSUPERVISOR] e ON e.DEPARTAMENTO_ID = d.DEPARTAMENTO_ID
        WHERE a.ID_SOLICITUD = @ID_SOLICITUD;

        -- Apertura del cursor
        OPEN cursorAprobaciones;

        -- Obtención del primer registro
        FETCH NEXT FROM cursorAprobaciones INTO @SECUENCIA, @ENCARGADO_APROBACION;

        -- Bucle para manejar los datos obtenidos del cursor
        WHILE @@FETCH_STATUS = 0
        BEGIN
            -- Insertar datos en la tabla APROBACIONSOLICITUD
            INSERT INTO APROBACIONSOLICITUD(
               SECUENCIA,
               RESPUESTA_SOLICITUD,
               ENCARGADO_APROBACION_ID,
               SOLICITUD_ID
             
            )
            VALUES (
               @SECUENCIA,
               @RESPUESTA_SOLICITUD,
               @ENCARGADO_APROBACION,
               @ID_SOLICITUD
        
            );

            -- Obtención del siguiente registro
            FETCH NEXT FROM cursorAprobaciones INTO @SECUENCIA, @ENCARGADO_APROBACION;
        END;

        -- Cierre del cursor
        CLOSE cursorAprobaciones;
        DEALLOCATE cursorAprobaciones;

		 exec [dbo].[NotificacionSolicitud]  @ID_SOLICITUD

    END TRY
    BEGIN CATCH
        INSERT INTO [dbo].[DB_ERRORES]
           ([UserName],
            [ErrorNumber],
            [ErrorState],
            [ErrorSeverity],
            [ErrorLine],
            [ErrorProcedure],
            [ErrorMessage],
            [ErrorDateTime])
        VALUES
          (SUSER_SNAME(),
           ERROR_NUMBER(),
           ERROR_STATE(),
           ERROR_SEVERITY(),
           ERROR_LINE(),
           ERROR_PROCEDURE(),
           ERROR_MESSAGE(),
           GETDATE());
    END CATCH;
END;