create database GestionPersonalProinsa

USE [GestionPersonalProinsa]
GO

/****** Object:  Table [dbo].[EMPLEADO] ******/
CREATE TABLE [dbo].[EMPLEADO](
	[ID_EMPLEADO] [bigint] IDENTITY(1,1) NOT NULL,
	[IDENTIFICACION] [varchar](20) NOT NULL,
	[NOMBRECOMPLETO] [varchar](250) NOT NULL,
	[FECHA_NACIMIENTO] [datetime] NOT NULL,
	[FECHA_INGRESO] [datetime] NOT NULL,
	[FOTO] [varchar](50) NOT NULL,
	[SALARIO] [decimal](10, 2) NOT NULL,
	[SALDO_VACACIONES] [int] NOT NULL,
	[CONTRASENNA] [varchar](50) NOT NULL,
	[ESTADO] [bit] NOT NULL,
	[TEMPORAL] [bit] NOT NULL,
	[VENCIMIENTO] [datetime] NOT NULL,
	[INTENTOS_FALLIDOS] [int] NOT NULL,
	[CARGO_ID] [bigint] NOT NULL,
	[ROL_ID] [bigint] NOT NULL,
	[CORREO_ID] [bigint] NOT NULL,
	[HORARIOLABORAL_ID] [bigint] NOT NULL,
	[DEPARTAMENTO_ID] [bigint] NOT NULL,
CONSTRAINT [PK_EMPLEADO_ID] 
PRIMARY KEY CLUSTERED 
(
	[ID_EMPLEADO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[CARGO] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CARGO](
	[ID_CARGO] [bigint] IDENTITY(1,1) NOT NULL,
	[NOMBRE_CARGO] [varchar](50) NULL,
	[DESCRIPCION] [varchar](200) NULL,
CONSTRAINT [PK_CARGO_ID]
PRIMARY KEY CLUSTERED 
(
	[ID_CARGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[CORREO] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CORREO](
	[ID_CORREO] [bigint] IDENTITY(1,1) NOT NULL,
	[CORREO] [varchar](255) NULL,
CONSTRAINT [PK_CORREO_ID]
PRIMARY KEY CLUSTERED 
(
	[ID_CORREO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[DIRRECCION] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIRRECCION](
	[ID_DIRECCION] [bigint] IDENTITY(1,1) NOT NULL,
	[DIRRECION] [varchar](600) NULL,
CONSTRAINT [PK_DIRRECCION_ID]
PRIMARY KEY CLUSTERED 
(
	[ID_DIRECCION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[EMPLEADODIRRECCION] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EMPLEADODIRRECCION](
	[ID_EMPLEADODIRRECCION] [bigint] IDENTITY(1,1) NOT NULL,
	[EMPLEADO_ID] [bigint] NOT NULL,
	[DIRRECION_ID] [bigint] NOT NULL,
CONSTRAINT [PK_EMPLEADODIRRECCION_ID]
PRIMARY KEY CLUSTERED 
(
	[ID_EMPLEADODIRRECCION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[TELEFONO] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TELEFONO](
	[ID_TELEFONO] [bigint] IDENTITY(1,1) NOT NULL,
	[TELEFONO] [varchar](22) NULL,
CONSTRAINT [PK_TELEFONO_ID]
PRIMARY KEY CLUSTERED 
(
	[ID_TELEFONO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[EMPLEADOTELEFONO] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EMPLEADOTELEFONO](
	[ID_EMPLEADOTELEFONO] [bigint] IDENTITY(1,1) NOT NULL,
	[EMPLEADO_ID] [bigint] NOT NULL,
	[TELEFONO_ID] [bigint] NOT NULL,
CONSTRAINT [PK_EMPLEADOTELEFONO_ID]
PRIMARY KEY CLUSTERED 
(
	[ID_EMPLEADOTELEFONO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[ROL] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ROL](
	[ID_ROL] [bigint] IDENTITY(1,1) NOT NULL,
	[NOMBRE_ROL] [varchar](50) NULL,
	[DESCRIPCION] [varchar](100) NULL,
 CONSTRAINT [PK_ROL_ID] 
 PRIMARY KEY CLUSTERED 
(
	[ID_ROL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[HORARIOLABORAL] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HORARIOLABORAL](
	[ID_HORARIOLABORAL] [bigint] IDENTITY(1,1) NOT NULL,
	[NOMBREHL] [varchar] (50) NOT NULL,
	[DESCRIPCION] [varchar](200) NULL,
	[HORA_INGRESO] [int] NULL,
	[HORA_SALIDA] [int] NULL,
CONSTRAINT [PK_HORARIOLABORAL_ID]
PRIMARY KEY CLUSTERED 
(
	[ID_HORARIOLABORAL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[CAPACITACION] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CAPACITACION](
	[ID_CAPACION] [bigint] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [varchar](100) NULL,
	[INSTITUCION] [varchar](100) NULL,
	[LINK] [varchar] (100) NULL,
	[CERTIFICACION] [varchar](100) NULL,
	[FECHA_FINALIZACION] [datetime] NULL,
	[CANTIDAD_HORAS] [int] NULL,
	[ESTADO] [bit] NULL,
CONSTRAINT [PK_CAPACITACION_ID]
PRIMARY KEY CLUSTERED 
(
	[ID_CAPACION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[EMPLEADOCAPACITACION] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EMPLEADOCAPACITACION](
	[ID_EMPLEADOCAPACITACION] [bigint] IDENTITY(1,1) NOT NULL,
	[CAPACITACION_ID] [bigint] NOT NULL,
	[EMPLEADO_ID] [bigint] NOT NULL,
CONSTRAINT [PK_EMPLEADOCAPACITACION_ID]
PRIMARY KEY CLUSTERED 
(
	[ID_EMPLEADOCAPACITACION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[SOLICITUD] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SOLICITUD](
	[ID_SOLICITUD] [bigint] IDENTITY(1,1) NOT NULL,
	[FECHA_SOLICITUD] [datetime] NOT NULL,
	[FECHA_INICIO] [datetime] NOT NULL,
	[FECHA_FINAL] [datetime] NOT NULL,
	[COMENTARIO] [varchar](200) NULL,
	[DIAS] [int] NOT NULL,
	[DETALLE] [varchar](300) NULL,
	[ESTADO_SOLICITUD] [char](10) NULL,
	[SOLICITANTE_ID] [bigint] NOT NULL,
	[TIPOSOLICITUD_ID] [bigint] NOT NULL,
 CONSTRAINT [PK_SOLICITUD_ID] 
 PRIMARY KEY CLUSTERED 
(
	[ID_SOLICITUD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[TIPOSOLICITUD] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPOSOLICITUD](
	[ID_TIPOSOLICITUD] [bigint] IDENTITY(1,1) NOT NULL,
	[NOMBRE_TIPO_SOLICITUD] [varchar](50) NULL,
	[DESCRIPCION] [varchar](100) NULL,
CONSTRAINT [PK_TIPOSOLICITUD_ID] 
PRIMARY KEY CLUSTERED 
(
	[ID_TIPOSOLICITUD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[APROBACIONSOLICITUD] ******/
CREATE TABLE [dbo].[APROBACIONSOLICITUD](
	[ID_APROBACIONSOLICITUD] [bigint] IDENTITY(1,1) NOT NULL,
	[FECHA_APROBACIONSOLICITUD] [datetime] NOT NULL,
	[SECUENCIA] [int] NULL,
	[RESPUESTA_SOLICITUD] [char](10) NOT NULL,
	[COMENTARIO] [varchar](200) NULL,
	[ENCARGADO_APROBACION_ID] [bigint] NOT NULL,
	[SOLICITUD_ID] [bigint] NOT NULL,
 CONSTRAINT [PK_APROBACIONSOLICITUD_ID] 
 PRIMARY KEY CLUSTERED 
(
	[ID_APROBACIONSOLICITUD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[REGISTROACTIVIDAD] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REGISTROACTIVIDAD](
	[ID_REGISTROACTIVIDAD] [bigint] IDENTITY(1,1) NOT NULL,
	[FECHA_INICIO] [datetime] NULL,
	[FECHA_FINAL] [datetime] NULL,
	[DETALLE] [varchar](500) NULL,
	[TIPOACTIVIDAD_ID] [bigint] NOT NULL,
	[EMPLEADO_ID] [bigint] NOT NULL,
CONSTRAINT [PK_REGISTROACTIVIDAD_ID] 
PRIMARY KEY CLUSTERED 
(
	[ID_REGISTROACTIVIDAD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[TIPOACTIVIDAD] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPOACTIVIDAD](
	[ID_TIPOACTIVIDAD] [bigint] IDENTITY(1,1) NOT NULL,	
	[NOMBRE_TIPO_CTIVIDAD] [varchar] (50) NULL,
	[DESCRIPCION] [varchar](100) NULL,
CONSTRAINT [PK_TIPOACTIVIDAD_ID]
PRIMARY KEY CLUSTERED 
(
	[ID_TIPOACTIVIDAD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[DEPARTAMENTO] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEPARTAMENTO](
	[ID_DEPARTAMENTO] [bigint] IDENTITY(1,1) NOT NULL,
	[NOMBRE_DEPARTAMENTO] [varchar] (50) NULL,
	[DESCRIPCION] [varchar](100) NOT NULL,
 CONSTRAINT [PK_DEPARTAMENTO_ID]
 PRIMARY KEY CLUSTERED 
(
	[ID_DEPARTAMENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[DEPARTAMENTOSUPERVISOR] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEPARTAMENTOSUPERVISOR](
    [ID_DEPARTAMENTOSUPERVISOR] [bigint] IDENTITY(1,1) NOT NULL,
	[EMPLEADO_ID] [bigint] NOT NULL,
	[DEPARTAMENTO_ID] [bigint] NOT NULL,
CONSTRAINT [PK_DEPARTAMENTOSUPERVISOR_ID]
PRIMARY KEY CLUSTERED 
(
	[ID_DEPARTAMENTOSUPERVISOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[FLUJOAPROBACION] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FLUJOAPROBACION](
	[ID_FLUJOAPROBACION] [bigint] IDENTITY(1,1) NOT NULL,
	[SECUENCIA] [int] NOT NULL,
	[DEPARTAMENTO_APROBACION_ID] [bigint] NULL,
	[DEPARTAMENTO_ID] [bigint] NOT NULL,
 CONSTRAINT [PK_FLUJOAPROBACION_ID]
 PRIMARY KEY CLUSTERED 
(
	[ID_FLUJOAPROBACION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[EMPLEADODOCUMENTO] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EMPLEADODOCUMENTO](
	[ID_EMPLEADODOCUMENTO] [bigint] IDENTITY(1,1) NOT NULL,
	[NOMBRE_DOCUMENTO] [varchar](50) NULL,
	[COMENTARIO] [varchar](200) NULL,
	[TIPODOCUMENTO_ID] [bigint] NULL,
	[EMPLEADO_ID] [bigint] NULL,
 CONSTRAINT [PK_EMPLEADODOCUMENTO_ID]
 PRIMARY KEY CLUSTERED 
(
	[ID_EMPLEADODOCUMENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[TIPODOCUMENTO] ******/
CREATE TABLE [dbo].[TIPODOCUMENTO](
	[ID_TIPODOCUMENTO] [bigint] IDENTITY(1,1) NOT NULL,
	[NOMBRE_TIPODOCUMENTO] [varchar] (50) NOT NULL,
	[DESCRIPCION] [varchar](200) NULL,
CONSTRAINT [PK_TIPODOCUMENTO_ID]
PRIMARY KEY CLUSTERED 
(
	[ID_TIPODOCUMENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[NOMINA] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NOMINA](
	[ID_NOMINA] [bigint] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [varchar](100) NULL,
	[PERIODO] [varchar](50) NULL,
	[FECHA_CALCULO] [datetime] NULL,
	[FECHA_PAGO] [datetime] NULL,
	[OBSERVACIONES] [varchar](500) NULL,
	[REVISIONES] [int] NULL,
	[FECHACREACION] [datetime] NULL,
	[FECHACAPROBACION] [datetime] NULL,
	[ESTADO] [bit] NULL,
	[TIPONOMINA_ID] [bigint] NULL,
	[CREADOR_ID] [bigint] NULL,
	[APROBADOR_ID] [bigint] NULL,
CONSTRAINT [PK_NOMINA_ID]
PRIMARY KEY CLUSTERED 
(
	[ID_NOMINA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[TIPONOMINA] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPONOMINA](
	[ID_TIPONOMINA] [bigint] IDENTITY(1,1) NOT NULL,
	[NOMBRE_NOMINA] [varchar](50) NULL,
	[DESCRIPCION] [varchar](200) NULL,
CONSTRAINT [PK_TIPONOMINA_ID]
PRIMARY KEY CLUSTERED 
(
	[ID_TIPONOMINA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[NOMINADETALLE] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NOMINADETALLE](
	[ID_NOMINADETALLE] [bigint] IDENTITY(1,1) NOT NULL,
	[HORAS_TRABAJADAS] [int] NULL,
    [HORAS_EXTRA] [int] NULL,
	[SALARIO_BRUTO] [decimal](10, 2) NULL,
	[SALARIO_NETO] [decimal](10, 2) NULL,
	[EMPLEADO_ID] [bigint] NOT NULL,
	[NOMINA_ID] [bigint] NOT NULL,
	[INGRESONOMINA_ID] [bigint] NOT NULL,
	[DEDUCCION_ID] [bigint] NOT NULL,
CONSTRAINT [PK_NOMINADETALLE_ID]
PRIMARY KEY CLUSTERED 
(
	[ID_NOMINADETALLE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[INGRESONOMINA] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INGRESONOMINA](
	[ID_INGRESONOMINA] [bigint] IDENTITY(1,1) NOT NULL,
	[MONTO] [decimal](10, 2) NULL,
	[DETALLE] [varchar](100) NULL,
	[INGRESO_ID] [bigint] NULL,
CONSTRAINT [PK_INGRESONOMINA_ID]
PRIMARY KEY CLUSTERED 
(
	[ID_INGRESONOMINA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[INGRESO] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INGRESO](
	[ID_INGRESO] [bigint] IDENTITY(1,1) NOT NULL,
	[NOMBRE_INGRESO] [varchar](50) NOT NULL,
	[DESCRIPCION] [varchar](200) NULL,
	[MONTO] [decimal](10, 2) NULL,
	[PORCENTAJE] [decimal](10, 2) NULL,
CONSTRAINT [PK_INGRESO_ID]
PRIMARY KEY CLUSTERED 
(
	[ID_INGRESO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[DEDUCCIONNOMINA] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEDUCCIONNOMINA](
	[ID_DEDUCIONNOMINA] [bigint] IDENTITY(1,1) NOT NULL,
	[MONTO] [decimal](10, 2) NULL,
	[DETALLE] [varchar](100) NULL,
	[DEDUCCION_ID] [bigint] NULL,
CONSTRAINT [PK_DEDUCCIONNOMINA_ID]
PRIMARY KEY CLUSTERED 
(
	[ID_DEDUCIONNOMINA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[DEDUCCION] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEDUCCION](
	[ID_DEDUCCION] [bigint] IDENTITY(1,1) NOT NULL,
	[NOMBRE_INGRESO] [varchar](50) NULL,
	[DESCRIPCION] [varchar](200) NULL,
	[MONTO] [decimal](10, 2) NULL,
	[PORCENTAJE] [decimal](10, 2) NULL,
CONSTRAINT [PK_DEDUCCION_ID]
PRIMARY KEY CLUSTERED 
(
	[ID_DEDUCCION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[DB_ERRORES]    Script Date: 5/25/2024 10:06:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DB_ERRORES](
	[ErrorID] [int] IDENTITY(1,1) NOT NULL,
	[UserName] [varchar](100) NULL,
	[ErrorNumber] [int] NULL,
	[ErrorState] [int] NULL,
	[ErrorSeverity] [int] NULL,
	[ErrorLine] [int] NULL,
	[ErrorProcedure] [varchar](max) NULL,
	[ErrorMessage] [varchar](max) NULL,
	[ErrorDateTime] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

/****** Llaves Foraneas ******/


ALTER TABLE [dbo].[EMPLEADO]  WITH CHECK ADD  CONSTRAINT [FK_EMPLEADO_CARGO] FOREIGN KEY([CARGO_ID])
REFERENCES [dbo].[CARGO] ([ID_CARGO])
GO
ALTER TABLE [dbo].[EMPLEADO] CHECK CONSTRAINT [FK_EMPLEADO_CARGO]
GO

ALTER TABLE [dbo].[EMPLEADO]  WITH CHECK ADD  CONSTRAINT [FK_EMPLEADO_ROL] FOREIGN KEY([ROL_ID])
REFERENCES [dbo].[ROL] ([ID_ROL])
GO
ALTER TABLE [dbo].[EMPLEADO] CHECK CONSTRAINT [FK_EMPLEADO_ROL]
GO

ALTER TABLE [dbo].[EMPLEADO]  WITH CHECK ADD  CONSTRAINT [FK_EMPLEADO_CORREO] FOREIGN KEY([CORREO_ID])
REFERENCES [dbo].[CORREO] ([ID_CORREO])
GO
ALTER TABLE [dbo].[EMPLEADO] CHECK CONSTRAINT [FK_EMPLEADO_CORREO]
GO

ALTER TABLE [dbo].[EMPLEADO]  WITH CHECK ADD  CONSTRAINT [FK_EMPLEADO_HORARIOLABORAL] FOREIGN KEY([HORARIOLABORAL_ID])
REFERENCES [dbo].[HORARIOLABORAL] ([ID_HORARIOLABORAL])
GO
ALTER TABLE [dbo].[EMPLEADO] CHECK CONSTRAINT [FK_EMPLEADO_HORARIOLABORAL]
GO

ALTER TABLE [dbo].[EMPLEADO]  WITH CHECK ADD  CONSTRAINT [FK_EMPLEADO_DEPARTAMENTO] FOREIGN KEY([DEPARTAMENTO_ID])
REFERENCES [dbo].[DEPARTAMENTO] ([ID_DEPARTAMENTO])
GO
ALTER TABLE [dbo].[EMPLEADO] CHECK CONSTRAINT [FK_EMPLEADO_DEPARTAMENTO]
GO

ALTER TABLE [dbo].[EMPLEADODIRRECCION]  WITH CHECK ADD  CONSTRAINT [FK_EMPLEADODIRRECCION_EMPLEADO] FOREIGN KEY([EMPLEADO_ID])
REFERENCES [dbo].[EMPLEADO] ([ID_EMPLEADO])
GO
ALTER TABLE [dbo].[EMPLEADODIRRECCION] CHECK CONSTRAINT [FK_EMPLEADODIRRECCION_EMPLEADO]
GO

ALTER TABLE [dbo].[EMPLEADODIRRECCION]  WITH CHECK ADD  CONSTRAINT [FK_EMPLEADODIRRECCION_DIRECCION] FOREIGN KEY([DIRRECION_ID])
REFERENCES [dbo].[DIRRECCION] ([ID_DIRECCION])
GO
ALTER TABLE [dbo].[EMPLEADODIRRECCION] CHECK CONSTRAINT [FK_EMPLEADODIRRECCION_DIRECCION]
GO

ALTER TABLE [dbo].[EMPLEADOTELEFONO]  WITH CHECK ADD  CONSTRAINT [FK_EMPLEADOTELEFONO_EMPLEADO] FOREIGN KEY([EMPLEADO_ID])
REFERENCES [dbo].[EMPLEADO] ([ID_EMPLEADO])
GO
ALTER TABLE [dbo].[EMPLEADOTELEFONO] CHECK CONSTRAINT [FK_EMPLEADOTELEFONO_EMPLEADO]
GO

ALTER TABLE [dbo].[EMPLEADOTELEFONO]  WITH CHECK ADD  CONSTRAINT [FK_EMPLEADOTELEFONO_TELEFONO] FOREIGN KEY([TELEFONO_ID])
REFERENCES [dbo].[TELEFONO] ([ID_TELEFONO])
GO
ALTER TABLE [dbo].[EMPLEADOTELEFONO] CHECK CONSTRAINT [FK_EMPLEADOTELEFONO_TELEFONO]
GO

ALTER TABLE [dbo].[EMPLEADOCAPACITACION]  WITH CHECK ADD  CONSTRAINT [FK_EMPLEADOCAPACITACION_EMPLEADO] FOREIGN KEY([EMPLEADO_ID])
REFERENCES [dbo].[EMPLEADO] ([ID_EMPLEADO])
GO
ALTER TABLE [dbo].[EMPLEADOCAPACITACION] CHECK CONSTRAINT [FK_EMPLEADOCAPACITACION_EMPLEADO]
GO

ALTER TABLE [dbo].[EMPLEADOCAPACITACION]  WITH CHECK ADD  CONSTRAINT [FK_EMPLEADOCAPACITACION_CAPACITACION] FOREIGN KEY([CAPACITACION_ID])
REFERENCES [dbo].[CAPACITACION] ([ID_CAPACION])
GO
ALTER TABLE [dbo].[EMPLEADOCAPACITACION] CHECK CONSTRAINT [FK_EMPLEADOCAPACITACION_CAPACITACION]
GO

ALTER TABLE [dbo].[SOLICITUD]  WITH CHECK ADD  CONSTRAINT [FK_SOLICITUD_EMPLEADO] FOREIGN KEY([SOLICITANTE_ID])
REFERENCES [dbo].[EMPLEADO] ([ID_EMPLEADO])
GO
ALTER TABLE [dbo].[SOLICITUD] CHECK CONSTRAINT [FK_SOLICITUD_EMPLEADO]
GO

ALTER TABLE [dbo].[SOLICITUD]  WITH CHECK ADD  CONSTRAINT [FK_SOLICITUD_TIPOSOLICITUD] FOREIGN KEY([TIPOSOLICITUD_ID])
REFERENCES [dbo].[TIPOSOLICITUD] ([ID_TIPOSOLICITUD])
GO
ALTER TABLE [dbo].[SOLICITUD] CHECK CONSTRAINT [FK_SOLICITUD_TIPOSOLICITUD]
GO

ALTER TABLE [dbo].[APROBACIONSOLICITUD]  WITH CHECK ADD  CONSTRAINT [FK_APROBACIONSOLICITUD_EMPLEADO] FOREIGN KEY([ENCARGADO_APROBACION_ID])
REFERENCES [dbo].[EMPLEADO] ([ID_EMPLEADO])
GO
ALTER TABLE [dbo].[APROBACIONSOLICITUD] CHECK CONSTRAINT [FK_APROBACIONSOLICITUD_EMPLEADO]
GO

ALTER TABLE [dbo].[APROBACIONSOLICITUD]  WITH CHECK ADD  CONSTRAINT [FK_APROBACIONSOLICITUD_SOLICITUD] FOREIGN KEY([SOLICITUD_ID])
REFERENCES [dbo].[SOLICITUD] ([ID_SOLICITUD])
GO
ALTER TABLE [dbo].[APROBACIONSOLICITUD] CHECK CONSTRAINT [FK_APROBACIONSOLICITUD_SOLICITUD]
GO

ALTER TABLE [dbo].[REGISTROACTIVIDAD]  WITH CHECK ADD  CONSTRAINT [FK_REGISTROACTIVIDAD_EMPLEADO] FOREIGN KEY([EMPLEADO_ID])
REFERENCES [dbo].[EMPLEADO] ([ID_EMPLEADO])
GO
ALTER TABLE [dbo].[REGISTROACTIVIDAD] CHECK CONSTRAINT [FK_REGISTROACTIVIDAD_EMPLEADO]
GO

ALTER TABLE [dbo].[REGISTROACTIVIDAD]  WITH CHECK ADD  CONSTRAINT [FK_REGISTROACTIVIDAD_TIPOACTIVIDAD] FOREIGN KEY([TIPOACTIVIDAD_ID])
REFERENCES [dbo].[TIPOACTIVIDAD] ([ID_TIPOACTIVIDAD])
GO
ALTER TABLE [dbo].[REGISTROACTIVIDAD] CHECK CONSTRAINT [FK_REGISTROACTIVIDAD_TIPOACTIVIDAD]
GO

ALTER TABLE [dbo].[DEPARTAMENTOSUPERVISOR]  WITH CHECK ADD  CONSTRAINT [FK_DEPARTAMENTOSUPERVISOR_EMPLEADO] FOREIGN KEY([EMPLEADO_ID])
REFERENCES [dbo].[EMPLEADO] ([ID_EMPLEADO])
GO
ALTER TABLE [dbo].[DEPARTAMENTOSUPERVISOR] CHECK CONSTRAINT [FK_DEPARTAMENTOSUPERVISOR_EMPLEADO]
GO

ALTER TABLE [dbo].[DEPARTAMENTOSUPERVISOR]  WITH CHECK ADD  CONSTRAINT [FK_DEPARTAMENTOSUPERVISOR_DEPARTAMENTO] FOREIGN KEY([DEPARTAMENTO_ID])
REFERENCES [dbo].[DEPARTAMENTO] ([ID_DEPARTAMENTO])
GO
ALTER TABLE [dbo].[DEPARTAMENTOSUPERVISOR] CHECK CONSTRAINT [FK_DEPARTAMENTOSUPERVISOR_DEPARTAMENTO]
GO

ALTER TABLE [dbo].[FLUJOAPROBACION]  WITH CHECK ADD  CONSTRAINT [FK_FLUJOAPROBACION_DEPARTAMENTO1] FOREIGN KEY([DEPARTAMENTO_APROBACION_ID])
REFERENCES [dbo].[DEPARTAMENTO] ([ID_DEPARTAMENTO])
GO
ALTER TABLE [dbo].[FLUJOAPROBACION] CHECK CONSTRAINT [FK_FLUJOAPROBACION_DEPARTAMENTO1]
GO

ALTER TABLE [dbo].[FLUJOAPROBACION]  WITH CHECK ADD  CONSTRAINT [FK_FLUJOAPROBACION_DEPARTAMENTO2] FOREIGN KEY([DEPARTAMENTO_ID])
REFERENCES [dbo].[DEPARTAMENTO] ([ID_DEPARTAMENTO])
GO
ALTER TABLE [dbo].[FLUJOAPROBACION] CHECK CONSTRAINT [FK_FLUJOAPROBACION_DEPARTAMENTO2]
GO

ALTER TABLE [dbo].[EMPLEADODOCUMENTO]  WITH CHECK ADD  CONSTRAINT [FK_EMPLEADODOCUMENTO_EMPLEADO] FOREIGN KEY([EMPLEADO_ID])
REFERENCES [dbo].[EMPLEADO] ([ID_EMPLEADO])
GO
ALTER TABLE [dbo].[EMPLEADODOCUMENTO] CHECK CONSTRAINT [FK_EMPLEADODOCUMENTO_EMPLEADO]
GO

ALTER TABLE [dbo].[EMPLEADODOCUMENTO]  WITH CHECK ADD  CONSTRAINT [FK_EMPLEADODOCUMENTO_TIPODOCUMENTO] FOREIGN KEY([TIPODOCUMENTO_ID])
REFERENCES [dbo].[TIPODOCUMENTO] ([ID_TIPODOCUMENTO])
GO
ALTER TABLE [dbo].[EMPLEADODOCUMENTO] CHECK CONSTRAINT [FK_EMPLEADODOCUMENTO_TIPODOCUMENTO]
GO

ALTER TABLE [dbo].[NOMINA]  WITH CHECK ADD  CONSTRAINT [FK_NOMINA_TIPONOMINA] FOREIGN KEY([TIPONOMINA_ID])
REFERENCES [dbo].[TIPONOMINA] ([ID_TIPONOMINA])
GO
ALTER TABLE [dbo].[NOMINA] CHECK CONSTRAINT [FK_NOMINA_TIPONOMINA]
GO

ALTER TABLE [dbo].[NOMINA]  WITH CHECK ADD  CONSTRAINT [FK_NOMINA_EMPLEADO1] FOREIGN KEY([CREADOR_ID])
REFERENCES [dbo].[EMPLEADO] ([ID_EMPLEADO])
GO
ALTER TABLE [dbo].[NOMINA] CHECK CONSTRAINT [FK_NOMINA_EMPLEADO1]
GO

ALTER TABLE [dbo].[NOMINA]  WITH CHECK ADD  CONSTRAINT [FK_NOMINA_EMPLEADO2] FOREIGN KEY([APROBADOR_ID])
REFERENCES [dbo].[EMPLEADO] ([ID_EMPLEADO])
GO
ALTER TABLE [dbo].[NOMINA] CHECK CONSTRAINT [FK_NOMINA_EMPLEADO2]
GO

ALTER TABLE [dbo].[NOMINADETALLE]  WITH CHECK ADD  CONSTRAINT [FK_NOMINADETALLE_EMPLEADO] FOREIGN KEY([EMPLEADO_ID])
REFERENCES [dbo].[EMPLEADO] ([ID_EMPLEADO])
GO
ALTER TABLE [dbo].[NOMINADETALLE] CHECK CONSTRAINT [FK_NOMINADETALLE_EMPLEADO]
GO

ALTER TABLE [dbo].[NOMINADETALLE]  WITH CHECK ADD  CONSTRAINT [FK_NOMINADETALLE_NOMINA] FOREIGN KEY([NOMINA_ID])
REFERENCES [dbo].[NOMINA] ([ID_NOMINA])
GO
ALTER TABLE [dbo].[NOMINADETALLE] CHECK CONSTRAINT [FK_NOMINADETALLE_NOMINA]
GO

ALTER TABLE [dbo].[NOMINADETALLE]  WITH CHECK ADD  CONSTRAINT [FK_NOMINADETALLE_INGRESONOMINA] FOREIGN KEY([INGRESONOMINA_ID])
REFERENCES [dbo].[INGRESONOMINA] ([ID_INGRESONOMINA])
GO
ALTER TABLE [dbo].[NOMINADETALLE] CHECK CONSTRAINT [FK_NOMINADETALLE_INGRESONOMINA]
GO

ALTER TABLE [dbo].[NOMINADETALLE]  WITH CHECK ADD  CONSTRAINT [FK_NOMINADETALLE_DEDUCCIONNOMINA] FOREIGN KEY([DEDUCCION_ID])
REFERENCES [dbo].[DEDUCCIONNOMINA] ([ID_DEDUCIONNOMINA])
GO
ALTER TABLE [dbo].[NOMINADETALLE] CHECK CONSTRAINT [FK_NOMINADETALLE_DEDUCCIONNOMINA]
GO

ALTER TABLE [dbo].[INGRESONOMINA]  WITH CHECK ADD  CONSTRAINT [FK_INGRESONOMINA_INGRESO] FOREIGN KEY([INGRESO_ID])
REFERENCES [dbo].[INGRESO] ([ID_INGRESO])
GO
ALTER TABLE [dbo].[INGRESONOMINA] CHECK CONSTRAINT [FK_INGRESONOMINA_INGRESO]
GO

ALTER TABLE [dbo].[DEDUCCIONNOMINA]  WITH CHECK ADD  CONSTRAINT [FK_DEDUCCIONNOMINA_DEDUCCION] FOREIGN KEY([DEDUCCION_ID])
REFERENCES [dbo].[DEDUCCION] ([ID_DEDUCCION])
GO
ALTER TABLE [dbo].[DEDUCCIONNOMINA] CHECK CONSTRAINT [FK_DEDUCCIONNOMINA_DEDUCCION]
GO

---CAMBIOS EN LA TABLA EMPLEADO

--IDENTIFICACION
ALTER TABLE EMPLEADO ALTER COLUMN IDENTIFICACION INT NULL ;
--NOMBRECOMPLETO
ALTER TABLE EMPLEADO ALTER COLUMN NOMBRECOMPLETO VARCHAR(250) NULL;
--FECHA_NACIMIENTO
ALTER TABLE EMPLEADO ALTER COLUMN FECHA_NACIMIENTO DATETIME NULL;
--FOTO
ALTER TABLE EMPLEADO ALTER COLUMN FOTO VARCHAR(250) NULL;
--SALARIO
ALTER TABLE EMPLEADO ALTER COLUMN SALARIO DECIMAL(10,2) NULL;
--SALDO VACACIONES
ALTER TABLE EMPLEADO ALTER COLUMN SALDO_VACACIONES  INT  NULL;
--FECHA_INGRESO
ALTER TABLE EMPLEADO ALTER COLUMN FECHA_INGRESO DATETIME NULL;
--------------------------------------------------------------
--CONTRASENNA
ALTER TABLE EMPLEADO DROP COLUMN CONTRASENNA
--TEMPORAL
ALTER TABLE EMPLEADO DROP COLUMN TEMPORAL
--VENCIMIENTO
ALTER TABLE EMPLEADO DROP COLUMN VENCIMIENTO
--ESTADO
ALTER TABLE EMPLEADO DROP COLUMN ESTADO
--INTENTOS FALLIDOS
ALTER TABLE EMPLEADO DROP COLUMN INTENTOS_FALLIDOS
--CARGO_ID
ALTER TABLE EMPLEADO ALTER COLUMN CARGO_ID  BIGINT  NULL;
--HORARIOLABORAL_ID
ALTER TABLE EMPLEADO ALTER COLUMN HORARIOLABORAL_ID BIGINT NULL
--DEPARMENTO_ID
ALTER TABLE EMPLEADO ALTER COLUMN DEPARTAMENTO_ID BIGINT NULL
--ROL_ID
ALTER TABLE EMPLEADO DROP CONSTRAINT FK_EMPLEADO_ROL
ALTER TABLE EMPLEADO DROP COLUMN ROL_ID;
--ELIMINACION DE LA TABLA 
DROP TABLE [ROL]

--INSERCION EN LA TABLA DE ROLES

INSERT INTO AspNetRoles(Id,[Name]) values('1','ADMINISTRADOR')
INSERT INTO AspNetRoles(Id,[Name]) values('2','RECURSOS HUMANOS')
INSERT INTO AspNetRoles(Id,[Name]) values('3','EMPLEADO')

---INSERCION EN LA TABLA DE CORREO
INSERT INTO CORREO(CORREO) VALUES ('tcamacho@proinsaca.com')

---INSERCION EN LA TABLA AspNetUsers

INSERT [dbo].[AspNetUsers] ([Id], [UserName], [NormalizedUserName], [Email], [NormalizedEmail], [EmailConfirmed], [PasswordHash], [SecurityStamp], [ConcurrencyStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEnd], [LockoutEnabled], [AccessFailedCount]) VALUES (N'36ba66b6-a40a-4444-8cdd-14e8b92f60c6', N'tcamacho@proinsalat.com', N'TCAMACHO@PROINSALAT.COM', N'tcamacho@proinsalat.com', N'TCAMACHO@PROINSALAT.COM', 0, NULL, N'Z5YELD7SL32TKYYH655NXVMOANZFKBLD', N'73ec4b02-dd4a-4be5-b692-ad82b52b7274', NULL, 0, 0, NULL, 1, 0)
GO
SET IDENTITY_INSERT [dbo].[EMPLEADO] ON 
--INSERCION EN EMPLEADO
SET IDENTITY_INSERT EMPLEADO ON;
INSERT [dbo].[EMPLEADO] ([ID_EMPLEADO], [IDENTIFICACION], [NOMBRECOMPLETO], [FECHA_NACIMIENTO], [FECHA_INGRESO], [FOTO], [SALARIO], [SALDO_VACACIONES], [CARGO_ID], [CORREO_ID], [HORARIOLABORAL_ID], [DEPARTAMENTO_ID]) VALUES (1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL)
SET IDENTITY_INSERT [dbo].[EMPLEADO] OFF
GO

--INSERCION EN AspNetUserRoles

INSERT INTO AspNetUserRoles(UserId,RoleId) VALUES('36ba66b6-a40a-4444-8cdd-14e8b92f60c6','1')
---PROCEDIMIENTOS ALMACENADOS
create procedure ObtenerInformacionEmpleado
as begin
SELECT 
    em.IDENTIFICACION,
    em.NOMBRECOMPLETO,
    em.FECHA_NACIMIENTO,
    em.FOTO,
    co.CORREO,
	roles.Name as ROL,
    de.DESCRIPCION AS DEPARTAMENTO,
    ca.NOMBRE_CARGO AS CARGO,
    ho.DESCRIPCION AS HORARIO,
    em.SALARIO,
    em.SALDO_VACACIONES ,
	direc.DIRRECION
FROM 
    EMPLEADO em
LEFT JOIN 
    CARGO ca ON em.CARGO_ID = ca.ID_CARGO
INNER JOIN 
    CORREO co ON co.ID_CORREO = em.CORREO_ID
LEFT JOIN  
    HORARIOLABORAL ho ON ho.ID_HORARIOLABORAL = em.HORARIOLABORAL_ID
LEFT JOIN 
    DEPARTAMENTO de ON de.ID_DEPARTAMENTO = em.DEPARTAMENTO_ID

inner join AspNetUsers users on users.Email=co.CORREO

inner join AspNetUserRoles userol on userol.UserId=users.Id

inner join AspNetRoles roles on roles.Id=userol.RoleId

left join EMPLEADODIRRECCION empledirec on empledirec.EMPLEADO_ID=em.ID_EMPLEADO

inner join DIRRECCION direc on direc.ID_DIRECCION=empledirec.DIRRECION_ID
end
---TRIGGERS
GO
CREATE TRIGGER [dbo].[trg_AfterInsert_AspNetUsers]
ON [dbo].[AspNetUsers]
AFTER INSERT
AS
BEGIN
BEGIN TRY
    -- Validar si el correo existe
    IF NOT EXISTS (
        SELECT 1
        FROM CORREO C
        INNER JOIN INSERTED I ON C.CORREO = I.Email
    )
    BEGIN
        -- Insertar el correo en la tabla CORREO 
        INSERT INTO CORREO (CORREO)
        SELECT DISTINCT Email 
        FROM INSERTED 
        -- Insertar en la tabla EMPLEADO con el CORREO_ID correspondiente al correo.
        INSERT INTO EMPLEADO (CORREO_ID)
        SELECT C.ID_CORREO
        FROM CORREO C
        INNER JOIN INSERTED I ON C.CORREO = I.Email
        -- Insertar en la tabla AspNetUserRoles con el ROL 1(Empleado)
        INSERT INTO AspNetUserRoles (UserId, RoleId)
        SELECT I.Id, 1
        FROM INSERTED I;
    END
END TRY
BEGIN CATCH
    INSERT INTO [dbo].[DB_ERRORES]
           ([UserName]
           ,[ErrorNumber]
           ,[ErrorState]
           ,[ErrorSeverity]
           ,[ErrorLine]
           ,[ErrorProcedure]
           ,[ErrorMessage]
           ,[ErrorDateTime])
    VALUES
    (SUSER_SNAME(),
    ERROR_NUMBER(),
    ERROR_STATE(),
    ERROR_SEVERITY(),
    ERROR_LINE(),
    ERROR_PROCEDURE(),
    ERROR_MESSAGE(),
    GETDATE());
END CATCH
END;
GO

ALTER TABLE [dbo].[AspNetUsers] ENABLE TRIGGER [trg_AfterInsert_AspNetUsers]
GO
