create  PROCEDURE [dbo].[SaldoVacacionesReporte]

AS
BEGIN
   

    SELECT 
        e.IDENTIFICACION,
        e.ID_EMPLEADO,
        e.NOMBRECOMPLETO,
        e.SALARIO,
        e.SALDO_VACACIONES,
        ca.NOMBRE_CARGO AS CARGO,

		
   
        CASE WHEN e.ESTADO = 1 THEN 'Activo' ELSE 'Inactivo' END AS ESTADO
        
    FROM EMPLEADO e
    LEFT JOIN CORREO c ON e.CORREO_ID = c.ID_CORREO
    LEFT JOIN CARGO ca ON e.CARGO_ID = ca.ID_CARGO
    LEFT JOIN HORARIOLABORAL hl ON e.HORARIOLABORAL_ID = hl.ID_HORARIOLABORAL
    LEFT JOIN DEPARTAMENTO d ON e.DEPARTAMENTO_ID = d.ID_DEPARTAMENTO
    
END
